<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Analysis - local employment</title>

<script src="site_libs/header-attrs-2.22/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.0/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.0/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#section-TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#section-TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="section-TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">CTE impacts on migration trends in SW Minnesota</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Summary of results</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-gear"></span>
     
    Data prep and summaries
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="k12enrollment.html">K12Enrollment</a>
    </li>
    <li>
      <a href="k12orgs.html">K12Orgs</a>
    </li>
    <li>
      <a href="act.html">ACT</a>
    </li>
    <li>
      <a href="ap.html">AP</a>
    </li>
    <li>
      <a href="cteenrollment.html">CTEEnrollment</a>
    </li>
    <li>
      <a href="ctedemographics.html">CTEDemographics</a>
    </li>
    <li>
      <a href="cteintensity.html">CTEIntensity</a>
    </li>
    <li>
      <a href="assessments.html">Assessments</a>
    </li>
    <li>
      <a href="sat.html">SAT</a>
    </li>
    <li>
      <a href="nscenrollment.html">National Student Clearinghouse - enrollment</a>
    </li>
    <li>
      <a href="nsccompletions.html">National Student Clearinghouse - completions</a>
    </li>
    <li>
      <a href="employment.html">Employment</a>
    </li>
    <li>
      <a href="unemployment.html">Unemployment</a>
    </li>
    <li>
      <a href="avgwages.html">Average wages</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-gear"></span>
     
    Analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="analysis_methods.html">Analysis methods</a>
    </li>
    <li>
      <a href="analysis_local_employment.html">Local employment</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="section-header">



<h1 class="title toc-ignore">Analysis - local employment</h1>

</div>


<p><br></p>
<p>The master dataset is composed of 38,154 rows. Each row represents an
individual that graduated (StatusEnd = 8 or 9) from a high school
located in EDR 6W, EDR 6E, and EDR 8 between 2008 and 2019.</p>
<p>The master dataset is also composed of 100 columns. Columns mainly
represent various socio-economic, demographic, and educational career
characteristics of the indivdual as well as a few characteristics of the
high school geographic from which they graduated (i.e. county
unemployment).</p>
<p>Here is a list of all the variables that will be included in the
model and a description of each.</p>
<ul>
<li><strong>Individual Characteristics</strong>
<ul>
<li><strong>hs.grad.year:</strong> year the individual graduated high
school</li>
<li><strong>Gender:</strong>
<ul>
<li>M = male</li>
<li>F = female</li>
</ul></li>
<li><strong>LimitedEnglishProficiencyIndicator:</strong>
<ul>
<li>Y = identified as having limited english proficiency at some point
between 10th and 12th grade, otherwise N.</li>
</ul></li>
<li><strong>HomelessIndicator:</strong>
<ul>
<li>Y = the individual was identified as homeless at any point between
10th and 12th grade, otherwise N.</li>
</ul></li>
<li><strong>economic.status:</strong>
<ul>
<li>1 = the individual was eligible for free or reduced lunch (codes
1,2,4,5) at any point between 10th and 12th grade, otherwise 0.</li>
</ul></li>
<li><strong>pseo.participant:</strong>
<ul>
<li>1 = the individual participated in a PSEO course sometime between
10th and 12th grade, otherwise 0.</li>
</ul></li>
<li><strong>SpecialEdStatus:</strong>
<ul>
<li>1 = the individual required special education services at some point
between 10th and 12th grade, otherwise 0.</li>
</ul></li>
<li><strong>non.english.home:</strong>
<ul>
<li>1 = the individual was identifed as having English as not the
primary langauge spoken at home between 10th and 12th grad, otherwise
0.</li>
</ul></li>
<li><strong>n.years.attended:</strong> the number of years the
individual attended the high school and is identified in the dataset.
Max is 6 years.</li>
<li><strong>ACTCompositeScore:</strong> the composite ACT score of the
individual. If the ACT was not taken, the individual is NA.</li>
<li><strong>ap.exam:</strong>
<ul>
<li>1 = the individual took an AP exam at some point,</li>
<li>0 = the individual did not take an AP exam.</li>
</ul></li>
<li><strong>total.cte.courses.taken:</strong> the total number of CTE
courses the individual has taken in their career since 10th grade.</li>
<li><strong>cte.0 through cte.26:</strong> the number of CTE courses
taken in each CTE career cluster, where;
<ul>
<li>0 = NULL - no career field or career name</li>
<li>1 = Agriculture, Food, and Natural Resources<br />
</li>
<li>2 = Architecture &amp; Construction</li>
<li>3 = Manufacturing<br />
</li>
<li>4 = Transportation, Distribution &amp; Logistics<br />
</li>
<li>5 = Information Technology<br />
</li>
<li>6 = Marketing, Sales &amp; Service<br />
</li>
<li>7 = Finance</li>
<li>8 = Hospitality &amp; Tourism<br />
</li>
<li>9 = Business, Management &amp; Administrative<br />
</li>
<li>10 = Health Science &amp; Health Occupations<br />
</li>
<li>11 = Human Services</li>
<li>12 = Arts, A/V Technology, &amp; Communication<br />
</li>
<li>14 = Science, Technology, Engineering, &amp; Mathematics<br />
</li>
<li>21 = Work-Experience-Disadvantaged<br />
</li>
<li>22 = Work Experience-Handicapped<br />
</li>
<li>23 = Work Experience-Handicapped (16-20+ on IEP)</li>
<li>24 = Work Experience/Career Exploration (age 14-15 on IEP)</li>
<li>25 = Diversified Occupations</li>
<li>26 = Administrative Only</li>
</ul></li>
<li><strong>cte.achievement:</strong> three indicators with
<ul>
<li>“CTE concentrator or completor” being one,</li>
<li>“CTE participant” meaning they took a CTE course but was not a
concentrator or completor, and,</li>
<li>“No CTE” meaning they didn’t take a CTE course.</li>
</ul></li>
<li><strong>english.learner:</strong>
<ul>
<li>1 = the individual was identified as an “english learner” at least
one time between 10th and 12th grade, otherwise 0.</li>
</ul></li>
<li><strong>MCA.M &amp; MCA.R &amp; MCA.S:</strong> this is the
Minnesota Comprehensive Assessment tests for reading, math and science.
Each individual is given 1 of 4 grades for each subject;
<ul>
<li>1 = Does not meet standards</li>
<li>2 = Partially meets standards</li>
<li>3 = Meets standards</li>
<li>4 = Exceeds standards</li>
</ul></li>
<li><strong>sat.taken:</strong>
<ul>
<li>1 = individual took the SAT at some point between 10th and 12th
grade, otherwise 0.</li>
</ul></li>
<li><strong>attended.ps:</strong>
<ul>
<li>Yes = the individual lattended a post-secondary education
institution, otherwise No.</li>
</ul></li>
<li><strong>first.InstitutionSector:</strong> this identifies the
institution sector of their first post-secondary school. There are 10
different sectors.
<ul>
<li>1 - Public, 4-year or above</li>
<li>2 - Private not-for-profit, 4-year or above</li>
<li>3 - Private for-profit, 4-year or above</li>
<li>4 - Public, 2-year</li>
<li>5 - Private not-for-profit, 2-year</li>
<li>6 - Private for-profit, 2-year</li>
<li>7 - Public, less-than 2-year</li>
<li>8 - Private not-for-profit, less-than 2-year</li>
<li>9 - Private for-profit, less-than 2-year</li>
<li>10 - multiple sectors (if attended multiple institutions)</li>
<li>99 - Sector unknown (not active)</li>
<li>NA - did not attend post-secondary</li>
</ul></li>
<li><strong>ps.sector.(1-10):</strong> each number represents “1 through
10” institution sector types.
<ul>
<li>1 = the individual attended the particular post-secondary
institution sector, otherwise 0.</li>
</ul></li>
<li><strong>ps.attended.in.same.ruca/edr:</strong> two columns which
identify whether the PersonID ever attended a post-secondary institution
in the same RUCA category or economic development region as their high
school.
<ul>
<li>“Outside ruca/edr” = individual never attended a post-secondary
institution within the RUCA category or economic development region as
their high school.</li>
<li>“In same ruca/edr” = individual attended a post-secondary
institution(s) only within the same RUCA category or economic
development region as their high school.</li>
<li>“Inside and outside same ruca/edr” = individual attended
post-secondary institutions within and outside the same RUCA category or
EDR as their high school.</li>
<li>“Never attended ps” = individual never attended a post-secondary
institution.</li>
</ul></li>
<li><strong>ps.attended.in.same.pr:</strong> one column which identifies
whether the individual attended a post-secondary institution within the
three economic development regions being rearched (EDR 6W, EDF 6E, and
EDR 8).
<ul>
<li>“In same PR” = individual attended a post-secondary institution(s)
in one of the three EDRs only.</li>
<li>“Outside PR” = individual never attended a post-secondary
institution(s) in one the three EDRs.</li>
<li>“Inside and outside same PR” = individual attended post-secondary
institutions within and outside one of the three EDRs. “Never attended
ps” = individual never attended a post-secondary institution.</li>
</ul></li>
<li><strong>ps.attended.in.MN:</strong> one column which identifies
whether the individual attended a post-secondary institution within
Minnesota.
<ul>
<li>“In MN” = individual attended a post-secondary institution(s) in
Minnesota only.</li>
<li>“Outside MN” = individual never attended a post-secondary
institution(s) in Minnesota.</li>
<li>“Inside and outside MN” = individual attended a post-secondary
institution(s) inside and outside Minnesota.</li>
<li>“Never attended ps” = never attended post-secondary institution</li>
</ul></li>
<li><strong>ps.grad:</strong>
<ul>
<li>1 = the individual gradated from a post-secondary institution
otherwise 0.</li>
</ul></li>
<li><strong>ps.grad.InstitutionSector:</strong> the institution sector
of the post-secondary school from which an individual has graduated.
<ul>
<li>1-10 = the codes of the institution sector provided above.</li>
<li>“Never attended ps” = the individual never attended a post-secondary
institution</li>
<li>“Did not graduate” = the individual attended a post-secondary
institution but did not graduate.</li>
</ul></li>
<li><strong>highest.cred.level:</strong> an identifier of the highest
credential earned by the PersonID. The categories are;
<ul>
<li>Less than associate degree</li>
<li>Associate degree</li>
<li>Bachelors degree</li>
<li>Higher than bachelors degree.</li>
</ul></li>
<li><strong>ps.grad.in.same.ruca/edr:</strong> did the student graduate
from an institution located in the same RUCA category or EDR as their
high school.
<ul>
<li>“Outside ruca/edr” = individual never graduated from a
post-secondary institution within the RUCA category or economic
development region as their high school.</li>
<li>“In same ruca/edr” = individual graduated from a post-secondary
institution(s) only within the same RUCA category or economic
development region as their high school.</li>
<li>“Inside and outside same ruca/edr” = individual graduates from a
post-secondary institutions within and outside the same RUCA category or
EDR as their high school.</li>
<li>“Never attended ps” = individual never attended a post-secondary
institution.”PR” is whether they graduated from an institution within
the research area (three EDRs) and “MN” is whether they graduated from
an institution in Minnesota.</li>
<li>“Did not grad” = individual attended a post-secondary institution
but never graduated.</li>
</ul></li>
<li><strong>ps.grad.in.same.pr:</strong> one column indentifying whether
the individual graduated from a post-secondary institution in one of the
three economic development regions being research.
<ul>
<li>“In same PR” = individual graduated from a post-secondary
institution(s) in one of the three EDRs only.</li>
<li>“Outside PR” = individual never graduated from a post-secondary
institution(s) in one the three EDRs.</li>
<li>“Inside and outside same PR” = individual graduated from a
post-secondary institutions within and outside one of the three
EDRs.</li>
<li>“Never attended ps” = individual never attended a post-secondary
institution.</li>
<li>“Did not grad” = individual attended a post secondary institution
but did not graduate.</li>
</ul></li>
<li><strong>ps.grad.in.MN:</strong> one column indentifying whether the
individual graduated from a post-secondary institution located in
Minnesota.
<ul>
<li>“In MN” = individual graduated from a post-secondary institution(s)
in Minnesota.</li>
<li>“Outside MN” = individual never graduated from a post-secondary
institution(s) in Minnesota.</li>
<li>“Inside and outside MN” = individual graduated from a post-secondary
institutions within and outside Minnesota.</li>
<li>“Never attended ps” = individual never attended a post-secondary
institution.</li>
<li>“Did not grad” = individual attended a post secondary institution
but did not graduate.</li>
</ul></li>
<li><strong>mn.emp.record.hs.grad.year(.2 &amp; .7):</strong> did the
individual have a MN employment record the year of graduating high
school, two years after graduating, and seven years after graduating.
<ul>
<li>“MN emp record” = the individual had a MN employment record at that
time frame.</li>
<li>“No MN emp record” = the individual did not have a MN employment
record at that time frame.</li>
</ul></li>
<li><strong>meaningful.emp.hs.grad.year(.2 &amp; .7):</strong> did the
individual work 1,000 hours or more for one employer the year of
graduation, two years after graduation, and seven years after
graduation.
<ul>
<li>“Meaningful emp” = individual had meaningful employment in Minnesota
at the time frame.</li>
<li>“No meaninful emp” = individual did not have meaningful employment
in Minnesota at the time frame.</li>
<li>“No MN emp record” = the individual did not have a MN employment
record at that time frame.</li>
<li>“After 2019” = the timeframe for the individual (2 and/or 7 years
after graduating) would be after 2019 for which there is no data.</li>
</ul></li>
<li><strong>hs.grad.year.(2 &amp; 7).county.match:</strong> did the
individual have meaningful employment for an employer located in the
same county as their high school - the year of graduation, two years
after graduation, and seven years after graduation.
<ul>
<li>“Location match” = the individual had meaningful employment in
Minnesota and was in the same county as their high school at that time
frame.</li>
<li>“No location match” = the individual had meaningful employment in
Minnesota but NOT in the same county as their high school at that time
frame.</li>
<li>“No meaningful emp” = the individual did not have meaningful
employment at that time frame.</li>
<li>“No MN emp record” = the individual did not have a MN employment
record at that time frame.</li>
<li>“After 2019” = the time frame for the individual (2 and/or 7 years
after graduating) would be after 2019 for which there is no data.</li>
</ul></li>
<li><strong>hs.grad.year.(2 &amp; 7).edr.match:</strong> did the
individual have meaningful employment for an employer located in the
same EDR as their high school - the year of graduation, two years after
graduation, and seven years after graduation.
<ul>
<li>“Location match” = the individual had meaningful employment in
Minnesota and was in the same EDR as their high school at that time
frame.</li>
<li>“No location match” = the individual had meaningful employment in
Minnesota but NOT in the same EDR as their high school at that time
frame.</li>
<li>“No meaningful emp” = the individual did not have meaningful
employment at that time frame.</li>
<li>“No MN emp record” = the individual did not have a MN employment
record at that time frame.</li>
<li>“After 2019” = the time frame for the individual (2 and/or 7 years
after graduating) would be after 2019 for which there is no data.</li>
</ul></li>
<li><strong>hs.grad.year.(2 &amp; 7).region.match:</strong> did the
individual have meaningful employment in one of the three EDRs - the
year of graduation, two years after graduation, and seven years after
graduation.
<ul>
<li>“Location match” = the individual had meaningful employment in
Minnesota and was in one of the three research economic development
regions at that time frame.</li>
<li>“No location match” = the individual had meaningful employment in
Minnesota but NOT in one of the three EDRs at that time frame.</li>
<li>“No meaningful emp” = the individual did not have meaningful
employment at that time frame.</li>
<li>“No MN emp record” = the individual did not have a MN employment
record at that time frame.</li>
<li>“After 2019” = the time frame for the individual (2 and/or 7 years
after graduating) would be after 2019 for which there is no data.</li>
</ul></li>
<li><strong>hs.grad.year.state.match:</strong> did the individual have
meaningful employment for an employer located in Minnesota the year of
graduation, two years after graduation and seven years after graduation.
<ul>
<li>“Location match” = the individual had meaningful employment in
Minnesota.</li>
<li>“No meaningful emp” = the individual did not have meaningful
employment at that time frame.</li>
<li>“No MN emp record” = the individual did not have a MN employment
record at that time frame.</li>
<li>“After 2019” = the time frame for the individual (2 and/or 7 years
after graduating) would be after 2019 for which there is no data.</li>
</ul></li>
<li><strong>ind.match.hs.grad.year(.2 and .7):</strong> did the
individual have meaningful employment in an industry that matches a CTE
course they took - the year of graduation, two years after graduation
and seven years after graduation.
<ul>
<li>“Ind match” = the individual had meaningful employment in Minnesota
was working in an industry that corresponds to a career cluster of one
of their CTE courses.</li>
<li>“No ind match” = the individual took a CTE course, had meaningful
employment in Minnesota, but was not in an industry corresponding to one
of their CTE career clusters.</li>
<li>“No meaningful emp” = the individual had a MN employment record but
was not meaningful at that time frame.</li>
<li>“No MN emp record” = the individual did not have a MN employment
record at that time frame.</li>
<li>“After 2019” = the timeframe would have been after 2019 for which
there is no data.</li>
</ul></li>
</ul></li>
<li><strong>High School Characteristics</strong>
<ul>
<li><strong>K12OrganizationID:</strong> Identification code for each
high school in research region.</li>
<li><strong>countyfp:</strong> the fips code of the code in which the
high school is located.</li>
<li><strong>Dem_Desc:</strong> the RUCA category in which the high
school is located.</li>
<li><strong>edr:</strong> the economic development region in which the
high school is located.</li>
<li><strong>avg.cte.intensity:</strong> The purpose of the CTE intensity
measure is to determine whether a strong presence of CTE programming and
participation impacts migration patterns. The thinking is that there
will be plenty of students that may not dive deep into CTE coursework,
but just seeing it in your school and constantly being reminded of all
the local opportunities and occupational needs in the local area might
impact how a student views employment opportunities for themselves in
the future.We needed to come up with a measure of what the CTE
“intensity” was for each school by each year. To do this, Eric Shwankl,
Education Consultant with the Southwest West Central Service
Cooperative, came up with an ingenious way to measure “CTE intensity”
using the z-score (also called standard score). The z-score calculates
how far a value is (in terms of standard deviation) from the average in
the population. In this case z-score is used to measure how far one
schools CTE student participation % is from the mean of the percentage
of all schools that year, and how far one schools CTE courses offered
per student % is from the percentage of all schools for that year. This
particular column takes the average z-score from all the school
instances for each individual.</li>
<li><strong>avg.unemp.rate:</strong> the three year average unemployment
rate during an individuals Sophmore, Junior and Senior years.</li>
<li><strong>wages.3year.avg:</strong> the average county median
household income of an individuals SOphomore, Junior and Senior
years.</li>
</ul></li>
</ul>
<p><br></p>
<div id="section-method-steps" class="section level1">
<h1>Method steps</h1>
<p>There are a number of dependent variables for which we want to
measure independent variables. These are;</p>
<ul>
<li>hs.grad.year.county.match (2 &amp; 7)</li>
<li>hs.grad.year.edr.match (2 &amp; 7)</li>
<li>hs.grad.year.region.match (2 &amp; 7)</li>
<li>hs.grad.year.state.match (2 &amp; 7)</li>
<li>ind.match.hs.grad.year (2 &amp; 7)</li>
</ul>
<p>A few secondary ones include;</p>
<ul>
<li>meaningful.emp.hs.grad.year (2 &amp; 7)</li>
</ul>
<p>Let’s now test out our dataset so we know that it will work. With the
high number of independent variables, using best subsert selection
mthods will not work. There isn’t enough computing power. So we will
play around with stepwise methods.</p>
<p>We will test out just a few variables first before adding all of
them. Let’s us hs.grad.year.2.county.match_Location match as the
dependent variable.</p>
<ul>
<li>Dependent variable = hs.grad.year.2.county.match
<ul>
<li>Location match: The individual had meaningful employment in the same
county as their high school two years after graduation.</li>
<li>No location match: The individual had meaningful employment in
Minnesota but NOT in the same county as their high school.</li>
<li>No meaningful emp: The individual had a MN employment record but
employment was not meaningful.</li>
<li>Unknown: the individual had a MN employment record but was a
“Statewide” position so it is unknow location.</li>
<li>No MN emp record: The individual did not have a MN employment
record.</li>
</ul></li>
</ul>
<pre><code>## [1] &quot;PersonID&quot;                                  
## [2] &quot;hs.grad.year.2.county.match_Location match&quot;</code></pre>
<p><br></p>
<p>We did filter out all of the “After 2019” individuals so we are left
with 31,998 individuals.</p>
<p>The independent variables we will use to test our methods will
be;</p>
<ul>
<li>LimitedEnglishProficienyIndicator
<ul>
<li>Y = Yes</li>
<li>N = No</li>
</ul></li>
<li>HomelessIndicator
<ul>
<li>Y = Yes</li>
<li>N = No</li>
</ul></li>
<li>economic.status
<ul>
<li>1 = Free or reduced lunch</li>
<li>0 = No free or reduced lunch</li>
</ul></li>
<li>pseo.participant
<ul>
<li>1 = Yes</li>
<li>0 = No</li>
</ul></li>
<li>SpecialEdStatus
<ul>
<li>1 = Yes</li>
<li>0 = No</li>
</ul></li>
<li>non.english.home
<ul>
<li>1 = Yes</li>
<li>0 = No</li>
</ul></li>
<li>Dem_Desc
<ul>
<li>Entirely rural</li>
<li>Town/rural mix</li>
<li>Urban/town/rural mix</li>
</ul></li>
<li>edr
<ul>
<li>EDR 6E</li>
<li>EDR 6W</li>
<li>EDR 8</li>
</ul></li>
<li>ACTCompositeScore
<ul>
<li>Values</li>
</ul></li>
</ul>
<p><br></p>
<pre><code>##  [1] &quot;PersonID&quot;                           &quot;LimitedEnglishProficiencyIndicator&quot;
##  [3] &quot;HomelessIndicator&quot;                  &quot;economic.status&quot;                   
##  [5] &quot;pseo.participant&quot;                   &quot;SpecialEdStatus&quot;                   
##  [7] &quot;non.english.home&quot;                   &quot;Dem_Desc&quot;                          
##  [9] &quot;edr&quot;                                &quot;ACTCompositeScore&quot;                 
## [11] &quot;took.ACT&quot;</code></pre>
<p><br></p>
<p>The dataset with independent variables to test has 38,154
individuals. Now we will join the independent and dependent variable
datasets.</p>
<p><br></p>
<pre><code>##  [1] &quot;hs.grad.year.2.county.match.location.match&quot;
##  [2] &quot;LimitedEnglishProficiencyIndicator&quot;        
##  [3] &quot;HomelessIndicator&quot;                         
##  [4] &quot;economic.status&quot;                           
##  [5] &quot;pseo.participant&quot;                          
##  [6] &quot;SpecialEdStatus&quot;                           
##  [7] &quot;non.english.home&quot;                          
##  [8] &quot;Dem_Desc&quot;                                  
##  [9] &quot;edr&quot;                                       
## [10] &quot;ACTCompositeScore&quot;                         
## [11] &quot;took.ACT&quot;</code></pre>
<p><br></p>
<p>Okay, let’s test the entire model and see what comes up as being
significant.</p>
<p><br></p>
<pre><code>## 
## Call:
## glm(formula = hs.grad.year.2.county.match.location.match ~ LimitedEnglishProficiencyIndicator + 
##     HomelessIndicator + economic.status + pseo.participant + 
##     SpecialEdStatus + non.english.home + Dem_Desc + edr + took.ACT, 
##     family = binomial, data = master.test)
## 
## Coefficients:
##                                     Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                         -1.33818    0.05675 -23.578  &lt; 2e-16 ***
## LimitedEnglishProficiencyIndicatorY -0.37787    0.11604  -3.256  0.00113 ** 
## HomelessIndicatorY                  -0.25846    0.23510  -1.099  0.27162    
## economic.status1                     0.18433    0.03308   5.572 2.52e-08 ***
## pseo.participant1                   -0.44657    0.03806 -11.733  &lt; 2e-16 ***
## SpecialEdStatus1                    -0.13122    0.04420  -2.969  0.00299 ** 
## non.english.home1                    0.11145    0.05751   1.938  0.05265 .  
## Dem_DescTown/rural mix               0.48681    0.04959   9.817  &lt; 2e-16 ***
## Dem_DescUrban/town/rural mix         0.27786    0.06182   4.494 6.97e-06 ***
## edrEDR 6W- Upper Minnesota Valley   -0.55877    0.04740 -11.788  &lt; 2e-16 ***
## edrEDR 8 - Southwest                -0.27958    0.03459  -8.082 6.39e-16 ***
## took.ACTY                           -0.56530    0.03402 -16.615  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 29481  on 31997  degrees of freedom
## Residual deviance: 28410  on 31986  degrees of freedom
## AIC: 28434
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p><br></p>
<p>When running the entire model, we see the following coming up as
statistically significant;</p>
<ul>
<li>LimitedEnglishProficency1 = Less likely</li>
<li>economic.status1 = more likely to have meaningful employment in the
county two years after graduation if the the student was eligible for
free and/or reduced lunch</li>
<li>SpecialEdStatus = more likely to have meaningful employment in the
county two years after graduation if the student was indetified as
needing special education.</li>
<li>pseo.participant1 = the student was less likely to have meaningful
employment in the county two years after graduation if they participated
in PSEO.</li>
<li>Dem_DescTown/rural mix = more likely to have meaningful employment
in the county if they graduated from a high school located in a
town/rural mix county.</li>
<li>Dem_DescUrban/town/rural mix = more likely to have meaningful
employment in the county if they graduated from a high school located in
a urban/town/rural mix county.</li>
<li>edrEDR 6W- Upper Minnesota Valley = less likely to have meaninhful
employment in the county if they graduated from a high school located in
EDR 6W.</li>
<li>edrEDR 8 - Southwest = Less likely to have meaningful employment in
the county if they graduated from a high school located in EDR 8.</li>
<li>took.ACT = Likliness decreases if individual took the ACT.</li>
</ul>
<p>Let’s check to see if there are is any serious multicollinearity in
the datset.</p>
<p><br></p>
<pre><code>##                                        GVIF Df GVIF^(1/(2*Df))
## LimitedEnglishProficiencyIndicator 1.234311  1        1.110996
## HomelessIndicator                  1.005782  1        1.002887
## economic.status                    1.192506  1        1.092019
## pseo.participant                   1.152840  1        1.073704
## SpecialEdStatus                    1.141221  1        1.068280
## non.english.home                   1.358878  1        1.165709
## Dem_Desc                           1.184440  2        1.043226
## edr                                1.189961  2        1.044439
## took.ACT                           1.274021  1        1.128726</code></pre>
<p><br></p>
<p>Many of the independent variables are close to 1, indicating minor
collinearity. The largest one is non.english.home variable with 1.36,
but that isn’t really high enough to warrant it being removed from the
model.</p>
<p>Okay, let’s see what the steps do for us. We will start with backward
stepwise.</p>
<p><br></p>
<pre><code>## Start:  AIC=28434.42
## hs.grad.year.2.county.match.location.match ~ LimitedEnglishProficiencyIndicator + 
##     HomelessIndicator + economic.status + pseo.participant + 
##     SpecialEdStatus + non.english.home + Dem_Desc + edr + took.ACT
## 
##                                      Df Deviance   AIC
## - HomelessIndicator                   1    28412 28434
## &lt;none&gt;                                     28410 28434
## - non.english.home                    1    28414 28436
## - SpecialEdStatus                     1    28419 28441
## - LimitedEnglishProficiencyIndicator  1    28422 28444
## - economic.status                     1    28441 28463
## - Dem_Desc                            2    28524 28544
## - pseo.participant                    1    28553 28575
## - edr                                 2    28563 28583
## - took.ACT                            1    28686 28708
## 
## Step:  AIC=28433.69
## hs.grad.year.2.county.match.location.match ~ LimitedEnglishProficiencyIndicator + 
##     economic.status + pseo.participant + SpecialEdStatus + non.english.home + 
##     Dem_Desc + edr + took.ACT
## 
##                                      Df Deviance   AIC
## &lt;none&gt;                                     28412 28434
## - non.english.home                    1    28416 28436
## - SpecialEdStatus                     1    28421 28441
## - LimitedEnglishProficiencyIndicator  1    28423 28443
## - economic.status                     1    28442 28462
## - Dem_Desc                            2    28526 28544
## - pseo.participant                    1    28554 28574
## - edr                                 2    28564 28582
## - took.ACT                            1    28686 28706</code></pre>
<pre><code>## 
## Call:  glm(formula = hs.grad.year.2.county.match.location.match ~ LimitedEnglishProficiencyIndicator + 
##     economic.status + pseo.participant + SpecialEdStatus + non.english.home + 
##     Dem_Desc + edr + took.ACT, family = binomial, data = master.test)
## 
## Coefficients:
##                         (Intercept)  LimitedEnglishProficiencyIndicatorY  
##                             -1.3386                              -0.3785  
##                    economic.status1                    pseo.participant1  
##                              0.1819                              -0.4467  
##                    SpecialEdStatus1                    non.english.home1  
##                             -0.1316                               0.1125  
##              Dem_DescTown/rural mix         Dem_DescUrban/town/rural mix  
##                              0.4863                               0.2778  
##   edrEDR 6W- Upper Minnesota Valley                 edrEDR 8 - Southwest  
##                             -0.5580                              -0.2789  
##                           took.ACTY  
##                             -0.5647  
## 
## Degrees of Freedom: 31997 Total (i.e. Null);  31987 Residual
## Null Deviance:       29480 
## Residual Deviance: 28410     AIC: 28430</code></pre>
<p><br></p>
<p>Through the process, it only removes one varaible, HomeLessIndicator.
The final model is;</p>
<p>hs.grad.year.2.county.match_location.match = -1.3386 - (.3785 *
LimitedEnglishProficiencyY) + (.1819 * economic.status1) - (.4467 *
pseo.participant1) - (.1316 * SpecialEdStatus1) + (.1125 *
non.english.home1) + (.4863 * Dem_DescTown/rural mix) + (.2778 *
Dem_DescUrban/town/rural mix) - (.5580 * EDR 6W) - (.2789 * EDR 8) -
(.5647 * took.ACTY)</p>
<p>Let’s compare this model to stepping forward.</p>
<p><br></p>
<pre><code>## Start:  AIC=28434.42
## hs.grad.year.2.county.match.location.match ~ LimitedEnglishProficiencyIndicator + 
##     HomelessIndicator + economic.status + pseo.participant + 
##     SpecialEdStatus + non.english.home + Dem_Desc + edr + took.ACT</code></pre>
<pre><code>## 
## Call:  glm(formula = hs.grad.year.2.county.match.location.match ~ LimitedEnglishProficiencyIndicator + 
##     HomelessIndicator + economic.status + pseo.participant + 
##     SpecialEdStatus + non.english.home + Dem_Desc + edr + took.ACT, 
##     family = binomial, data = master.test)
## 
## Coefficients:
##                         (Intercept)  LimitedEnglishProficiencyIndicatorY  
##                             -1.3382                              -0.3779  
##                  HomelessIndicatorY                     economic.status1  
##                             -0.2585                               0.1843  
##                   pseo.participant1                     SpecialEdStatus1  
##                             -0.4466                              -0.1312  
##                   non.english.home1               Dem_DescTown/rural mix  
##                              0.1114                               0.4868  
##        Dem_DescUrban/town/rural mix    edrEDR 6W- Upper Minnesota Valley  
##                              0.2779                              -0.5588  
##                edrEDR 8 - Southwest                            took.ACTY  
##                             -0.2796                              -0.5653  
## 
## Degrees of Freedom: 31997 Total (i.e. Null);  31986 Residual
## Null Deviance:       29480 
## Residual Deviance: 28410     AIC: 28430</code></pre>
<p><br></p>
<p>Moving forward doesn’t end up eliminated any variables. Unlike
stepping backwards, this model includes the HomelessIndicator variable.
Here is what the model would look like;</p>
<p>hs.grad.year.2.county.match_location.match = -1.3382 - (.3779 *
LimitedEnglishProficiencyY) + - (.2585 * HomelessIndicatorY) + (.1843 *
economic.status1) - (.4466 * pseo.participant1) - (.1312 *
SpecialEdStatus1) + (.1114 * non.english.home1) + (.4868 *
Dem_DescTown/rural mix) + (.2779 * Dem_DescUrban/town/rural mix) -
(.5588 * EDR 6W) - (.2796 * EDR 8) - (.5653 * took.ACTY)</p>
<p>Despite the inclusion of the HomelessIndicator variable, the
coefficients are very similar to the backward step model.</p>
</div>
<div id="section-rethinking-independent-variables"
class="section level1">
<h1>Rethinking independent variables</h1>
<p>Okay, including all of the variables that I want might be a bit too
taxing. So let’s get a bit more particular about what to include.</p>
<ul>
<li>Demographics
<ul>
<li>hs.grad.year</li>
<li>Gender</li>
<li>LimitedEnglishProficiencyIndicator</li>
<li>HomelessIndicator</li>
<li>economic.status</li>
<li>pseo.participant</li>
<li>SpecialEdStatus</li>
<li>Dem_Desc</li>
<li>edr</li>
</ul></li>
<li>Education characteristics
<ul>
<li>ACTCompositeScore</li>
<li>ap.examp</li>
<li>total.cte.courses.taken</li>
<li>cte.1 - 26</li>
<li>cte.achievement</li>
<li>avg.cte.intensity</li>
<li>english.learner</li>
<li>MCA.M - MCA.S</li>
<li>attended.ps</li>
<li>highest.cred.level</li>
<li>ps.grad.InstitutionSector</li>
<li>took.ACT</li>
</ul></li>
<li>Geographic characteristics
<ul>
<li>avg.unemp.rate</li>
<li>wages.3year.avg</li>
</ul></li>
</ul>
<p>We will also try using LASSO regression which shrinks the estimators
towards 0.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#section-TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
