<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Analysis - local employment cross tabs</title>

<script src="site_libs/header-attrs-2.22/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="site_libs/d3-bundle-5.16.0/d3-bundle.min.js"></script>
<script src="site_libs/d3-lasso-0.0.5/d3-lasso.min.js"></script>
<script src="site_libs/save-svg-as-png-1.4.17/save-svg-as-png.min.js"></script>
<script src="site_libs/flatbush-4.0.0/flatbush.min.js"></script>
<link href="site_libs/ggiraphjs-0.4.6/ggiraphjs.min.css" rel="stylesheet" />
<script src="site_libs/ggiraphjs-0.4.6/ggiraphjs.min.js"></script>
<script src="site_libs/girafe-binding-0.8.7/girafe.js"></script>
<link href="site_libs/font-awesome-6.4.0/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.0/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#section-TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#section-TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="section-TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">CTE impacts on migration trends in SW Minnesota</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Summary of results</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-gear"></span>
     
    Data prep and summaries
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="k12enrollment.html">K12Enrollment</a>
    </li>
    <li>
      <a href="k12orgs.html">K12Orgs</a>
    </li>
    <li>
      <a href="act.html">ACT</a>
    </li>
    <li>
      <a href="ap.html">AP</a>
    </li>
    <li>
      <a href="cteenrollment.html">CTEEnrollment</a>
    </li>
    <li>
      <a href="ctedemographics.html">CTEDemographics</a>
    </li>
    <li>
      <a href="cteintensity.html">CTEIntensity</a>
    </li>
    <li>
      <a href="assessments.html">Assessments</a>
    </li>
    <li>
      <a href="sat.html">SAT</a>
    </li>
    <li>
      <a href="nscenrollment.html">National Student Clearinghouse - enrollment</a>
    </li>
    <li>
      <a href="nsccompletions.html">National Student Clearinghouse - completions</a>
    </li>
    <li>
      <a href="employment.html">Employment</a>
    </li>
    <li>
      <a href="unemployment.html">Unemployment</a>
    </li>
    <li>
      <a href="avgwages.html">Average wages</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-gear"></span>
     
    Analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="analysis_multiple_correspondence.html">Analysis - multiple correspondence analysis</a>
    </li>
    <li>
      <a href="analysis_local_employment_ct.html">Local employment cross tabs</a>
    </li>
    <li>
      <a href="review.html">For Review</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="section-header">



<h1 class="title toc-ignore">Analysis - local employment cross tabs</h1>

</div>


<p><br></p>
<p>The first research question is to analyze the factors that play into
whether an individual has meaningful employment within their high school
county, EDR, research region, and Minnesota at time X.</p>
<p>There are three “times” in which we checked to see if the individual
had meaningful employment within these geographies;</p>
<ol style="list-style-type: decimal">
<li>the same year as graduation</li>
<li>two years after graduation, and</li>
<li>seven years after graduation.</li>
</ol>
<p>Meaningful employment is determined by whether an individual worked
1,000 hours for an employer during time X. In addition, if the
individual worked 1,000 hours for that employer during another year, but
not for that exact “time X” year, it’s still considered
“meaningful”.</p>
<p>Due to time x potentially being passed the date of the latest data
(2019) for some individuals, the analysis below will filter out all
individuals where time x is after 2019.</p>
<p>There are a number of independent variables in the master dataset.
And they are likely to have significant colinearity, so we are going to
split them up into larger “Groups” that will then have sub groups. For
example, instead of modeling whether the institution sector from which
an individual has graduated from impacts the dependent variable, we will
just check to see if graduating from a post-seconary institution impacts
the dependent variable. If so, then we will dig deeper to see if the
institution type is significant.</p>
<p>The primary independent variables we will use in the model is the
following;</p>
<pre><code>## $LimitedEnglishProficiencyIndicator
## [1] &quot;factor&quot;
## 
## $pseo.participant
## [1] &quot;factor&quot;
## 
## $non.english.home
## [1] &quot;factor&quot;
## 
## $RaceEthnicity
## [1] &quot;factor&quot;
## 
## $Dem_Desc
## [1] &quot;factor&quot;
## 
## $edr
## [1] &quot;factor&quot;
## 
## $took.ACT
## [1] &quot;factor&quot;
## 
## $ap.exam
## [1] &quot;factor&quot;
## 
## $cte.achievement
## [1] &quot;factor&quot;
## 
## $english.learner
## [1] &quot;factor&quot;
## 
## $attended.ps
## [1] &quot;factor&quot;
## 
## $ps.grad
## [1] &quot;factor&quot;
## 
## $ps.grad.InstitutionSector
## [1] &quot;factor&quot;
## 
## $highest.cred.level
## [1] &quot;factor&quot;
## 
## $total.cte.courses.taken
## [1] &quot;numeric&quot;
## 
## $cte.0
## [1] &quot;numeric&quot;
## 
## $cte.1
## [1] &quot;numeric&quot;
## 
## $cte.2
## [1] &quot;numeric&quot;
## 
## $cte.3
## [1] &quot;numeric&quot;
## 
## $cte.4
## [1] &quot;numeric&quot;
## 
## $cte.5
## [1] &quot;numeric&quot;
## 
## $cte.6
## [1] &quot;numeric&quot;
## 
## $cte.7
## [1] &quot;numeric&quot;
## 
## $cte.8
## [1] &quot;numeric&quot;
## 
## $cte.9
## [1] &quot;numeric&quot;
## 
## $cte.10
## [1] &quot;numeric&quot;
## 
## $cte.11
## [1] &quot;numeric&quot;
## 
## $cte.12
## [1] &quot;numeric&quot;
## 
## $cte.14
## [1] &quot;numeric&quot;
## 
## $cte.21
## [1] &quot;numeric&quot;
## 
## $cte.22
## [1] &quot;numeric&quot;
## 
## $cte.23
## [1] &quot;numeric&quot;
## 
## $cte.24
## [1] &quot;numeric&quot;
## 
## $cte.25
## [1] &quot;numeric&quot;
## 
## $cte.26
## [1] &quot;numeric&quot;
## 
## $avg.cte.intensity
## [1] &quot;numeric&quot;
## 
## $MCA.M
## [1] &quot;numeric&quot;
## 
## $MCA.R
## [1] &quot;numeric&quot;
## 
## $MCA.S
## [1] &quot;numeric&quot;
## 
## $avg.unemp.rate
## [1] &quot;numeric&quot;
## 
## $wages.3year.avg
## [1] &quot;numeric&quot;</code></pre>
<p><br></p>
<div id="section-steps-in-analysis" class="section level1">
<h1>Steps in analysis</h1>
<p>Our dependent variable - the individual has meaningful employment in
same location X as their high school - has 4 different outcomes.</p>
<ol style="list-style-type: decimal">
<li>Location match: the individual has
<ul>
<li>a MN employment record at time X</li>
<li>has meaningful employment at time X</li>
<li>is employed in the same location X as their high school.</li>
</ul></li>
<li>No location match: the individual has
<ul>
<li>a MN employment record at time X</li>
<li>has meaningful employment at time X</li>
<li>does NOT have employment in the same location X as their high
school.</li>
</ul></li>
<li>No meaningful emp: the individual has
<ul>
<li>a MN employment record at time X</li>
<li>the employment is not meaningful at time X.</li>
</ul></li>
<li>No MN emp record: the individual has
<ul>
<li>NO MN employment record at time X.</li>
</ul></li>
</ol>
<p>Since we are most interested in whether an individual has meaningful
employment in region X at time X we will create two groups; 1. all
individuals that meet the criteria/outcome 1 from list above, and 2. all
remaining individuals.</p>
<p>For each time X we will analyze whether the independent variables are
good at predicting whether an individual has a MN employment record AND
has meaningful employment AND the meaningful employment is in the same
region X as their high school.</p>
<p>The structure of the analysis will look like this;</p>
<ul>
<li>Location match - county through region
<ul>
<li>For each region x
<ul>
<li>Summary chart</li>
</ul></li>
<li>For each time x (grad year, grad year +2, grad year +7)
<ul>
<li>Demographic variables</li>
<li>HS characteristic variables</li>
<li>HS enrollment variables</li>
<li>HS accomplishments</li>
<li>Post secondary (only gor grad year +2 and grad year +7)</li>
</ul></li>
</ul></li>
</ul>
<p>I’ll be using the Cramer’s v-square measure of association. The V^2
value is from 0 to 1 with 0 meaning there’s no association and a value
closer to 1 indicates a strong association.</p>
<p><br></p>
</div>
<div id="section-location-match---county" class="section level1">
<h1>Location match - county</h1>
<div id="section-summary-chart" class="section level2">
<h2>Summary chart</h2>
<p>The chart below provides the percentage of individuals in the dataset
that had meaningful employment in the same county as their high school
the year of their graduation, graduation year +2, and graduation year
+7. The percentage of individuals does increase with each subsequent
time X - 12.4% the year of gradation, 17.4% two years after graduation,
and 20% seven years after graduation.</p>
<p><br></p>
<div class="girafe html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-f0601f7b97e3da546915" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-f0601f7b97e3da546915">{"x":{"html":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='ggiraph-svg' role='img' id='svg_afa5490f_5048_4c68_a171_b84e49eb2912' viewBox='0 0 720 720'>\n <defs id='svg_afa5490f_5048_4c68_a171_b84e49eb2912_defs'>\n  <clipPath id='svg_afa5490f_5048_4c68_a171_b84e49eb2912_c1'>\n   <rect x='0' y='0' width='720' height='720'/>\n  <\/clipPath>\n  <clipPath id='svg_afa5490f_5048_4c68_a171_b84e49eb2912_c2'>\n   <rect x='58.64' y='95.9' width='655.88' height='555.58'/>\n  <\/clipPath>\n <\/defs>\n <g id='svg_afa5490f_5048_4c68_a171_b84e49eb2912_rootg' class='ggiraph-svg-rootg'>\n  <g clip-path='url(#svg_afa5490f_5048_4c68_a171_b84e49eb2912_c1)'>\n   <rect x='0' y='0' width='720' height='720' fill='#FFFFFF' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.75' stroke-linejoin='round' stroke-linecap='round' class='ggiraph-svg-bg'/>\n   <rect x='0' y='0' width='720' height='720' fill='#FFFFFF' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\n  <\/g>\n  <g clip-path='url(#svg_afa5490f_5048_4c68_a171_b84e49eb2912_c2)'>\n   <rect x='58.64' y='95.9' width='655.88' height='555.58' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\n   <polyline points='58.64,626.23 714.52,626.23' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\n   <polyline points='58.64,482.08 714.52,482.08' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\n   <polyline points='58.64,337.93 714.52,337.93' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\n   <polyline points='58.64,193.78 714.52,193.78' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\n   <polyline points='237.52,651.48 237.52,95.90' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\n   <polyline points='535.64,651.48 535.64,95.90' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\n   <rect id='svg_afa5490f_5048_4c68_a171_b84e49eb2912_e1' x='192.8' y='525.78' width='89.44' height='100.44' fill='#FC8D59' fill-opacity='1' stroke='none' data-id='1' title='grad year +2&amp;lt;br/&amp;gt;Match: 17.4%'/>\n   <rect id='svg_afa5490f_5048_4c68_a171_b84e49eb2912_e2' x='490.93' y='150.07' width='89.44' height='476.16' fill='#FC8D59' fill-opacity='1' stroke='none' data-id='2' title='grad year +2&amp;lt;br/&amp;gt;No match: 82.6%'/>\n   <rect id='svg_afa5490f_5048_4c68_a171_b84e49eb2912_e3' x='282.24' y='511.08' width='89.44' height='115.15' fill='#FEE090' fill-opacity='1' stroke='none' data-id='3' title='grad year +7&amp;lt;br/&amp;gt;Match: 20.0%'/>\n   <rect id='svg_afa5490f_5048_4c68_a171_b84e49eb2912_e4' x='580.36' y='164.77' width='89.44' height='461.46' fill='#FEE090' fill-opacity='1' stroke='none' data-id='4' title='grad year +7&amp;lt;br/&amp;gt;No match: 80.0%'/>\n   <rect id='svg_afa5490f_5048_4c68_a171_b84e49eb2912_e5' x='103.36' y='554.7' width='89.44' height='71.53' fill='#D73027' fill-opacity='1' stroke='none' data-id='5' title='grad year +0&amp;lt;br/&amp;gt;Match: 12.4%'/>\n   <rect id='svg_afa5490f_5048_4c68_a171_b84e49eb2912_e6' x='401.49' y='121.15' width='89.44' height='505.08' fill='#D73027' fill-opacity='1' stroke='none' data-id='6' title='grad year +0&amp;lt;br/&amp;gt;No match: 87.6%'/>\n   <polygon points='215.92,534.48 259.11,534.48 259.03,534.48 259.37,534.47 259.71,534.40 260.04,534.27 260.34,534.10 260.61,533.88 260.84,533.62 261.03,533.33 261.16,533.01 261.25,532.67 261.27,532.32 261.27,532.32 261.27,519.24 261.27,519.24 261.25,518.89 261.16,518.56 261.03,518.24 260.84,517.94 260.61,517.68 260.34,517.46 260.04,517.29 259.71,517.17 259.37,517.10 259.11,517.08 215.92,517.08 216.18,517.10 215.83,517.08 215.49,517.12 215.15,517.22 214.84,517.37 214.55,517.57 214.30,517.81 214.09,518.09 213.93,518.39 213.82,518.72 213.77,519.07 213.76,519.24 213.76,532.32 213.77,532.15 213.77,532.50 213.82,532.84 213.93,533.17 214.09,533.48 214.30,533.76 214.55,534.00 214.84,534.19 215.15,534.34 215.49,534.44 215.83,534.48' fill='#FC8D59' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='round'/>\n   <text x='217.36' y='530.88' font-size='10.67pt' font-family='Helvetica' fill='#FFFFFF' fill-opacity='1'>17.4%<\/text>\n   <polygon points='514.05,158.77 557.24,158.77 557.15,158.77 557.50,158.76 557.84,158.69 558.17,158.56 558.47,158.39 558.74,158.17 558.97,157.91 559.15,157.62 559.29,157.30 559.37,156.96 559.40,156.61 559.40,156.61 559.40,143.53 559.40,143.53 559.37,143.18 559.29,142.85 559.15,142.53 558.97,142.23 558.74,141.97 558.47,141.75 558.17,141.58 557.84,141.45 557.50,141.38 557.24,141.37 514.05,141.37 514.31,141.38 513.96,141.37 513.62,141.41 513.28,141.51 512.97,141.66 512.68,141.86 512.43,142.10 512.22,142.37 512.06,142.68 511.95,143.01 511.89,143.36 511.89,143.53 511.89,156.61 511.89,156.44 511.89,156.79 511.95,157.13 512.06,157.46 512.22,157.77 512.43,158.04 512.68,158.28 512.97,158.48 513.28,158.63 513.62,158.73 513.96,158.77' fill='#FC8D59' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='round'/>\n   <text x='515.49' y='155.17' font-size='10.67pt' font-family='Helvetica' fill='#FFFFFF' fill-opacity='1'>82.6%<\/text>\n   <polygon points='305.36,519.78 348.55,519.78 348.46,519.78 348.81,519.77 349.15,519.70 349.48,519.57 349.78,519.40 350.05,519.18 350.28,518.92 350.46,518.63 350.60,518.31 350.68,517.97 350.71,517.62 350.71,517.62 350.71,504.54 350.71,504.54 350.68,504.19 350.60,503.86 350.46,503.54 350.28,503.24 350.05,502.98 349.78,502.76 349.48,502.59 349.15,502.47 348.81,502.40 348.55,502.38 305.36,502.38 305.62,502.40 305.27,502.38 304.93,502.42 304.59,502.52 304.28,502.67 303.99,502.87 303.74,503.11 303.53,503.39 303.37,503.69 303.26,504.02 303.21,504.37 303.20,504.54 303.20,517.62 303.21,517.45 303.21,517.80 303.26,518.14 303.37,518.47 303.53,518.78 303.74,519.05 303.99,519.30 304.28,519.49 304.59,519.64 304.93,519.74 305.27,519.78' fill='#FEE090' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='round'/>\n   <text x='306.8' y='516.18' font-size='10.67pt' font-family='Helvetica' fill='#FFFFFF' fill-opacity='1'>20.0%<\/text>\n   <polygon points='603.49,173.47 646.68,173.47 646.59,173.47 646.94,173.46 647.28,173.39 647.60,173.26 647.91,173.09 648.18,172.87 648.41,172.61 648.59,172.32 648.73,172.00 648.81,171.66 648.84,171.31 648.84,171.31 648.84,158.23 648.84,158.23 648.81,157.88 648.73,157.55 648.59,157.23 648.41,156.93 648.18,156.67 647.91,156.45 647.60,156.28 647.28,156.16 646.94,156.09 646.68,156.07 603.49,156.07 603.75,156.09 603.40,156.07 603.05,156.11 602.72,156.21 602.41,156.36 602.12,156.56 601.87,156.80 601.66,157.08 601.50,157.38 601.39,157.71 601.33,158.06 601.33,158.23 601.33,171.31 601.33,171.14 601.33,171.49 601.39,171.83 601.50,172.16 601.66,172.47 601.87,172.75 602.12,172.99 602.41,173.18 602.72,173.33 603.05,173.43 603.40,173.47' fill='#FEE090' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='round'/>\n   <text x='604.93' y='169.87' font-size='10.67pt' font-family='Helvetica' fill='#FFFFFF' fill-opacity='1'>80.0%<\/text>\n   <polygon points='126.48,563.40 169.67,563.40 169.59,563.40 169.94,563.39 170.28,563.32 170.60,563.19 170.90,563.02 171.17,562.80 171.40,562.54 171.59,562.25 171.72,561.93 171.81,561.59 171.83,561.24 171.83,561.24 171.83,548.16 171.83,548.16 171.81,547.81 171.72,547.48 171.59,547.16 171.40,546.86 171.17,546.60 170.90,546.38 170.60,546.21 170.28,546.09 169.94,546.02 169.67,546.00 126.48,546.00 126.74,546.02 126.40,546.00 126.05,546.04 125.72,546.14 125.40,546.29 125.12,546.49 124.87,546.73 124.66,547.01 124.49,547.31 124.38,547.64 124.33,547.99 124.32,548.16 124.32,561.24 124.33,561.07 124.33,561.42 124.38,561.76 124.49,562.09 124.66,562.40 124.87,562.67 125.12,562.92 125.40,563.11 125.72,563.26 126.05,563.36 126.40,563.40' fill='#D73027' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='round'/>\n   <text x='127.92' y='559.8' font-size='10.67pt' font-family='Helvetica' fill='#FFFFFF' fill-opacity='1'>12.4%<\/text>\n   <polygon points='424.61,129.85 467.80,129.85 467.72,129.85 468.06,129.84 468.40,129.77 468.73,129.64 469.03,129.47 469.30,129.25 469.53,128.99 469.71,128.70 469.85,128.38 469.93,128.04 469.96,127.69 469.96,127.69 469.96,114.61 469.96,114.61 469.93,114.26 469.85,113.93 469.71,113.61 469.53,113.31 469.30,113.05 469.03,112.83 468.73,112.66 468.40,112.54 468.06,112.47 467.80,112.45 424.61,112.45 424.87,112.47 424.52,112.45 424.18,112.49 423.84,112.59 423.53,112.74 423.24,112.94 422.99,113.18 422.78,113.46 422.62,113.76 422.51,114.09 422.46,114.44 422.45,114.61 422.45,127.69 422.46,127.52 422.46,127.87 422.51,128.21 422.62,128.54 422.78,128.85 422.99,129.12 423.24,129.37 423.53,129.56 423.84,129.71 424.18,129.81 424.52,129.85' fill='#D73027' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='round'/>\n   <text x='426.05' y='126.25' font-size='10.67pt' font-family='Helvetica' fill='#FFFFFF' fill-opacity='1'>87.6%<\/text>\n  <\/g>\n  <g clip-path='url(#svg_afa5490f_5048_4c68_a171_b84e49eb2912_c1)'>\n   <text x='32.91' y='631.38' font-size='10.8pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0%<\/text>\n   <text x='24.9' y='487.23' font-size='10.8pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>25%<\/text>\n   <text x='24.9' y='343.08' font-size='10.8pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>50%<\/text>\n   <text x='24.9' y='198.93' font-size='10.8pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>75%<\/text>\n   <text x='216.72' y='666.72' font-size='10.8pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Match<\/text>\n   <text x='502.86' y='666.72' font-size='10.8pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>No match<\/text>\n   <rect x='213.26' y='700.12' width='346.65' height='14.4' fill='none' stroke='none'/>\n   <rect x='222.22' y='700.12' width='14.4' height='14.4' fill='none' stroke='none'/>\n   <rect x='222.93' y='700.83' width='12.98' height='12.98' fill='#D73027' fill-opacity='1' stroke='none'/>\n   <rect x='337.77' y='700.12' width='14.4' height='14.4' fill='none' stroke='none'/>\n   <rect x='338.48' y='700.83' width='12.98' height='12.98' fill='#FC8D59' fill-opacity='1' stroke='none'/>\n   <rect x='453.32' y='700.12' width='14.4' height='14.4' fill='none' stroke='none'/>\n   <rect x='454.03' y='700.83' width='12.98' height='12.98' fill='#FEE090' fill-opacity='1' stroke='none'/>\n   <text x='247.58' y='712.47' font-size='10.8pt' font-family='Arial'>grad year +0<\/text>\n   <text x='363.13' y='712.47' font-size='10.8pt' font-family='Arial'>grad year +2<\/text>\n   <text x='478.68' y='712.47' font-size='10.8pt' font-family='Arial'>grad year +7<\/text>\n   <text x='5.48' y='67.18' font-size='13.5pt' font-family='Arial'>The percentage of individuals with meaningful employment in same county as their high<\/text>\n   <text x='5.48' y='86.62' font-size='13.5pt' font-family='Arial'>school increases for each subsequent Time X<\/text>\n   <text x='5.48' y='20.94' font-size='16.2pt' font-weight='bold' font-family='Arial'>Meaningful employment in same county as high school for each<\/text>\n   <text x='5.48' y='44.27' font-size='16.2pt' font-weight='bold' font-family='Arial'>time X as share of total individuals<\/text>\n  <\/g>\n <\/g>\n<\/svg>","js":null,"uid":"svg_afa5490f_5048_4c68_a171_b84e49eb2912","ratio":1,"settings":{"tooltip":{"css":".tooltip_SVGID_ { padding:5px;background:black;color:white;border-radius:2px;text-align:left; ; position:absolute;pointer-events:none;z-index:999;}","placement":"doc","opacity":0.9,"offx":10,"offy":10,"use_cursor_pos":true,"use_fill":false,"use_stroke":false,"delay_over":200,"delay_out":500},"hover":{"css":".hover_data_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\ntext.hover_data_SVGID_ { stroke:none;fill:orange; }\ncircle.hover_data_SVGID_ { fill:orange;stroke:black; }\nline.hover_data_SVGID_, polyline.hover_data_SVGID_ { fill:none;stroke:orange; }\nrect.hover_data_SVGID_, polygon.hover_data_SVGID_, path.hover_data_SVGID_ { fill:orange;stroke:none; }\nimage.hover_data_SVGID_ { stroke:orange; }","reactive":true,"nearest_distance":null},"hover_inv":{"css":""},"hover_key":{"css":".hover_key_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\ntext.hover_key_SVGID_ { stroke:none;fill:orange; }\ncircle.hover_key_SVGID_ { fill:orange;stroke:black; }\nline.hover_key_SVGID_, polyline.hover_key_SVGID_ { fill:none;stroke:orange; }\nrect.hover_key_SVGID_, polygon.hover_key_SVGID_, path.hover_key_SVGID_ { fill:orange;stroke:none; }\nimage.hover_key_SVGID_ { stroke:orange; }","reactive":true},"hover_theme":{"css":".hover_theme_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\ntext.hover_theme_SVGID_ { stroke:none;fill:orange; }\ncircle.hover_theme_SVGID_ { fill:orange;stroke:black; }\nline.hover_theme_SVGID_, polyline.hover_theme_SVGID_ { fill:none;stroke:orange; }\nrect.hover_theme_SVGID_, polygon.hover_theme_SVGID_, path.hover_theme_SVGID_ { fill:orange;stroke:none; }\nimage.hover_theme_SVGID_ { stroke:orange; }","reactive":true},"select":{"css":".select_data_SVGID_ { fill:red;stroke:gray; }","type":"none","only_shiny":true,"selected":[]},"select_inv":{"css":""},"select_key":{"css":".select_key_SVGID_ { fill:red;stroke:black;cursor:pointer; }\ntext.select_key_SVGID_ { stroke:none;fill:red; }\ncircle.select_key_SVGID_ { fill:red;stroke:black; }\nline.select_key_SVGID_, polyline.select_key_SVGID_ { fill:none;stroke:red; }\nrect.select_key_SVGID_, polygon.select_key_SVGID_, path.select_key_SVGID_ { fill:red;stroke:none; }\nimage.select_key_SVGID_ { stroke:red; }","type":"single","only_shiny":true,"selected":[]},"select_theme":{"css":".select_theme_SVGID_ { fill:red;stroke:black;cursor:pointer; }\ntext.select_theme_SVGID_ { stroke:none;fill:red; }\ncircle.select_theme_SVGID_ { fill:red;stroke:black; }\nline.select_theme_SVGID_, polyline.select_theme_SVGID_ { fill:none;stroke:red; }\nrect.select_theme_SVGID_, polygon.select_theme_SVGID_, path.select_theme_SVGID_ { fill:red;stroke:none; }\nimage.select_theme_SVGID_ { stroke:red; }","type":"single","only_shiny":true,"selected":[]},"zoom":{"min":1,"max":1,"duration":300},"toolbar":{"position":"topright","pngname":"diagram","tooltips":null,"hidden":[],"delay_over":200,"delay_out":500},"sizing":{"rescale":false,"width":1}}},"evals":[],"jsHooks":[]}</script>
<p><br></p>
</div>
<div id="section-cross-tabs---time-x-grad-year" class="section level2">
<h2>Cross tabs - Time X = grad year</h2>
<p>Now let’s examine whether there are any relationships between these
individuals and the independent variables.</p>
<p><br></p>
<div id="section-demographic-variables" class="section level3 tabset">
<h3 class="tabset">Demographic variables</h3>
<p><strong>Race/Ethnicity:</strong> The crosstabs indicate a
relationship between whether an individual has meaningful employment in
the same county as their high school the year they graduate and the
individual’s race/ethnicy. The p-value was 0, however the Cramer’s V^2
value was 0.068, indicating a weak association. Highlights in the table
include;</p>
<ul>
<li>A larger proportion of black individuals (16.6%) had meaningful
employment in their high school county compared to AI, Asian/PI and
White individuals.</li>
<li>A larger observed number of Black individuals had meaningful
employment in the same county as their high school than what was
expected - 124 individuals vs. 93 expected.</li>
<li>A larger proportion of hispanic individuals (19.9%) had meaningful
employment in their high school county compared to all other
races/ethnicities.</li>
<li>A larger observed number of hispanic individuals had meaningful
employment in the same county as their high school than what was
expected - 549 observed vs. 341 expected.</li>
</ul>
<div id="section-raceethnicity" class="section level4">
<h4>Race/Ethnicity</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="6">
RaceEthnicity
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
AI
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Asian/PI
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Black
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Hispanic
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Unknown
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
White
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">52</span><br><span
style="color:#339999;">49</span><br><span
style="color:#339933;">13 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">132</span><br><span
style="color:#339999;">132</span><br><span
style="color:#339933;">12.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">124</span><br><span
style="color:#339999;">93</span><br><span
style="color:#339933;">16.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">549</span><br><span
style="color:#339999;">341</span><br><span
style="color:#339933;">19.9 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3</span><br><span
style="color:#339999;">5</span><br><span
style="color:#339933;">7.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3860</span><br><span
style="color:#339999;">4100</span><br><span
style="color:#339933;">11.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">4720</span><br><span
style="color:#339999;">4720</span><br><span
style="color:#339933;">12.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">347</span><br><span
style="color:#339999;">350</span><br><span
style="color:#339933;">87 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">935</span><br><span
style="color:#339999;">935</span><br><span
style="color:#339933;">87.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">624</span><br><span
style="color:#339999;">655</span><br><span
style="color:#339933;">83.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2208</span><br><span
style="color:#339999;">2416</span><br><span
style="color:#339933;">80.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">37</span><br><span
style="color:#339999;">35</span><br><span
style="color:#339933;">92.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">29283</span><br><span
style="color:#339999;">29043</span><br><span
style="color:#339933;">88.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">33434</span><br><span
style="color:#339999;">33434</span><br><span
style="color:#339933;">87.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">399</span><br><span
style="color:#339999;">399</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1067</span><br><span
style="color:#339999;">1067</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">748</span><br><span
style="color:#339999;">748</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">2757</span><br><span
style="color:#339999;">2757</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">40</span><br><span
style="color:#339999;">40</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">33143</span><br><span
style="color:#339999;">33143</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">38154</span><br><span
style="color:#339999;">38154</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="8">
χ<sup>2</sup>=173.956 · df=5 · Cramer’s V=0.068 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
</div>
<div id="section-high-school-characteristic-variables"
class="section level3 tabset">
<h3 class="tabset">High school characteristic variables</h3>
<p><strong>Dem_Desc:</strong> The p-value indicates that we can reject
the null hypothesis and acknowledge that the variables may have a
relationship. The Cramer’s V^2 value is only 0.053, indicating that the
relationships are weak. Highlights from the table include;</p>
<ul>
<li>Individuals from entirely rural high schools had a significantly
lower proportion of individuals that had meaningful employment in the
same county as their high school - 8.6% compared to 11.1% in
urban/town/rural mix and 13.4% in town/rural mix.</li>
<li>Individuals from entirely rural high schools had a significantly
lower observed number of individuals that had meaningful employment in
the same county as their high school - 476 observed vs. 684
expected.</li>
</ul>
<p><br></p>
<p><strong>EDR:</strong> The p-value indicates that we can reject the
null hypothesis and acknowledge that the variables may have a
relationship. The Cramer’s V^2 value however is only 0.050, indicating
the associations are weak. Highlights in the table include;</p>
<ul>
<li>EDR 6W had the lowest proportion of individuals that had meaningful
employment in the same county as their high school the year of
graduation - 9.7% compared to 12% in EDR 8 and 14.2% in EDR 6E.</li>
<li>EDR 6W had a significantly lower number of individuals that had
meaningful employment in the same county as their high school the year
of graduation - 714 observed vs. 911 expected.</li>
</ul>
<p><br></p>
<p><strong>avg.unemployment.rate:</strong> The ANOVA table does indicate
a relationship between whether an individual has meaningful employment
in the same county as their high school the year of graduation and the
average unemployment rate in that county. It states that as unemployment
increases, the likliness of having “match” increases as well.</p>
<p><br></p>
<p><strong>wages.3year.avg:</strong> No relationship.</p>
<div id="section-dem_desc" class="section level4">
<h4>Dem_Desc</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="3">
Dem_Desc
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Entirely rural
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Town/rural mix
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Urban/town/rural mix
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">476</span><br><span
style="color:#339999;">684</span><br><span
style="color:#339933;">8.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3575</span><br><span
style="color:#339999;">3293</span><br><span
style="color:#339933;">13.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">669</span><br><span
style="color:#339999;">743</span><br><span
style="color:#339933;">11.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">4720</span><br><span
style="color:#339999;">4720</span><br><span
style="color:#339933;">12.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">5055</span><br><span
style="color:#339999;">4847</span><br><span
style="color:#339933;">91.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">23043</span><br><span
style="color:#339999;">23325</span><br><span
style="color:#339933;">86.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">5336</span><br><span
style="color:#339999;">5262</span><br><span
style="color:#339933;">88.9 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">33434</span><br><span
style="color:#339999;">33434</span><br><span
style="color:#339933;">87.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">5531</span><br><span
style="color:#339999;">5531</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">26618</span><br><span
style="color:#339999;">26618</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">6005</span><br><span
style="color:#339999;">6005</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">38154</span><br><span
style="color:#339999;">38154</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="5">
χ<sup>2</sup>=108.284 · df=2 · Cramer’s V=0.053 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-edr" class="section level4">
<h4>EDR</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="3">
edr
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
EDR 6E- Southwest<br>Central
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
EDR 6W- Upper<br>Minnesota Valley
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
EDR 8 - Southwest
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1985</span><br><span
style="color:#339999;">1725</span><br><span
style="color:#339933;">14.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">714</span><br><span
style="color:#339999;">911</span><br><span
style="color:#339933;">9.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2021</span><br><span
style="color:#339999;">2084</span><br><span
style="color:#339933;">12 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">4720</span><br><span
style="color:#339999;">4720</span><br><span
style="color:#339933;">12.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">11956</span><br><span
style="color:#339999;">12216</span><br><span
style="color:#339933;">85.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">6650</span><br><span
style="color:#339999;">6453</span><br><span
style="color:#339933;">90.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">14828</span><br><span
style="color:#339999;">14765</span><br><span
style="color:#339933;">88 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">33434</span><br><span
style="color:#339999;">33434</span><br><span
style="color:#339933;">87.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">13941</span><br><span
style="color:#339999;">13941</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">7364</span><br><span
style="color:#339999;">7364</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">16849</span><br><span
style="color:#339999;">16849</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">38154</span><br><span
style="color:#339999;">38154</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="5">
χ<sup>2</sup>=95.669 · df=2 · Cramer’s V=0.050 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-avg.unemployment.rate" class="section level4">
<h4>avg.unemployment.rate</h4>
<pre><code>##                Df Sum Sq Mean Sq F value  Pr(&gt;F)   
## dep.var         1     15  15.025   8.406 0.00374 **
## Residuals   38152  68198   1.788                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = avg.unemp.rate ~ dep.var, data = data)
## 
## $dep.var
##                      diff        lwr       upr     p adj
## No match-Match 0.06027224 0.01952656 0.1010179 0.0037407</code></pre>
<p><br></p>
</div>
<div id="section-wages.3yr.avg" class="section level4">
<h4>wages.3yr.avg</h4>
<pre><code>##                Df    Sum Sq  Mean Sq F value Pr(&gt;F)
## dep.var         1 2.191e+07 21910331   1.172  0.279
## Residuals   38152 7.130e+11 18687369</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = wages.3year.avg ~ dep.var, data = data)
## 
## $dep.var
##                    diff       lwr      upr     p adj
## No match-Match -72.7829 -204.5257 58.95995 0.2788948</code></pre>
<p><br></p>
</div>
</div>
<div id="section-high-school-enrollment-variables"
class="section level3 tabset">
<h3 class="tabset">High school enrollment variables</h3>
<p><strong>LimitedEnglishProficiencyIndicator:</strong> The p-value
indicates that we can reject the NULL hypothesis and acknowledge there
may be a relationship between whether an individual has meaningful
employment in the same county as their high school the year of
graduation and if the individual has limited english proficiency.
However, the Cramer’s V^2 value is only .026 indicating a weak
relationship. Highlights from the table include;</p>
<ul>
<li>A significantly larger proportion of individuals that had limited
english proficiency had meaningful employment in the same county as
their high school the year of graduation - 18.1% vs. 12.2% for
individuals that did not have limited english proficiency.</li>
<li>A significantly larger number of individuals with limited english
proficiency worked in the same county as their high school than expected
- 146 observed vs. 100 expected.</li>
</ul>
<p><br></p>
<p><strong>pseo.participant:</strong> The p-value indicates that we can
reject the NULL hypothesis and acknowledge there may be a relationship
between whether an individual has meaningful employment in the same
county as their high school the year of graduation and whether they
participated in PSEO classes. However, the Cramer’s V^2 value is only
.088 indicating a weak relationship. Highlights from the table
include;</p>
<ul>
<li>A significantly larger proportion of individuals that did NOT
participate in PSEO classes had meaningful employment in the same county
as their high school the year of graduation - 14.5% vs. 8.4% for
individuals that did participate in PSEO.</li>
<li>A significantly larger number of individuals that did NOT
participate in PSEO had meaningful employment in the same county as
their high school the year of graduation - 3,608 observed vs. 3,084
expected.</li>
</ul>
<p><br></p>
<p><strong>non.english.home:</strong> The p-value indicates that we can
reject the NULL hypothesis and acknowledge there may be a relationship
between whether an individual has meaningful employment in the same
county as their high school the year of graduation and whether the
individual had someone in their home where english wasn’t the primary
language. However, the Cramer’s V^2 value is only .060 indicating a weak
relationship. Highlights from the table include;</p>
<ul>
<li>A significantly larger proportion of individuals where english
wasn’t the primary language at home had meaningful employment in the
same county as their high school the year of graduation - 18.8%
vs. 11.8% for individuals where English was the primary language at
home.</li>
<li>The observed vs expected was also significantly different for this
group - 623 observed vs. 411 expected.</li>
</ul>
<p><br></p>
<p><strong>english.learner</strong>: The p-value indicates that we can
reject the NULL hypothesis and acknowledge there may be a relationship
between whether an individual has meaningful employment in the same
county as their high school the year of graduation and whether the
individual had someone in their home where english wasn’t the primary
language. However, the Cramer’s V^2 value is only .027 indicating a weak
relationship. Highlights from the table include;</p>
<ul>
<li>A larger proportion of individuals categorized as english learners
had meaningful employment in the same county as their high school -
16.1% vs. 12.2% of individuals not designated as english learners.</li>
<li>This same group had a larger number of individuals that expected -
333 observed vs. 256 expected.</li>
</ul>
<div id="section-limitedenglishproficiencyindicator"
class="section level4">
<h4>LimitedEnglishProficiencyIndicator</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
LimitedEnglishProficiencyIndicator
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
N
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Y
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4574</span><br><span
style="color:#339999;">4620</span><br><span
style="color:#339933;">12.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">146</span><br><span
style="color:#339999;">100</span><br><span
style="color:#339933;">18.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">4720</span><br><span
style="color:#339999;">4720</span><br><span
style="color:#339933;">12.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">32775</span><br><span
style="color:#339999;">32729</span><br><span
style="color:#339933;">87.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">659</span><br><span
style="color:#339999;">705</span><br><span
style="color:#339933;">81.9 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">33434</span><br><span
style="color:#339999;">33434</span><br><span
style="color:#339933;">87.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">37349</span><br><span
style="color:#339999;">37349</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">805</span><br><span
style="color:#339999;">805</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">38154</span><br><span
style="color:#339999;">38154</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=24.678 · df=1 · Cramer’s V=0.026 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-pseo.participant" class="section level4">
<h4>pseo.participant</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
pseo.participant
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
0
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3608</span><br><span
style="color:#339999;">3084</span><br><span
style="color:#339933;">14.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1112</span><br><span
style="color:#339999;">1636</span><br><span
style="color:#339933;">8.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">4720</span><br><span
style="color:#339999;">4720</span><br><span
style="color:#339933;">12.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">21321</span><br><span
style="color:#339999;">21845</span><br><span
style="color:#339933;">85.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">12113</span><br><span
style="color:#339999;">11589</span><br><span
style="color:#339933;">91.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">33434</span><br><span
style="color:#339999;">33434</span><br><span
style="color:#339933;">87.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">24929</span><br><span
style="color:#339999;">24929</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">13225</span><br><span
style="color:#339999;">13225</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">38154</span><br><span
style="color:#339999;">38154</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=292.625 · df=1 · φ=0.088 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-non.english.home" class="section level4">
<h4>non.english.home</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
non.english.home
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
0
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4097</span><br><span
style="color:#339999;">4309</span><br><span
style="color:#339933;">11.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">623</span><br><span
style="color:#339999;">411</span><br><span
style="color:#339933;">18.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">4720</span><br><span
style="color:#339999;">4720</span><br><span
style="color:#339933;">12.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">30738</span><br><span
style="color:#339999;">30526</span><br><span
style="color:#339933;">88.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2696</span><br><span
style="color:#339999;">2908</span><br><span
style="color:#339933;">81.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">33434</span><br><span
style="color:#339999;">33434</span><br><span
style="color:#339933;">87.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">34835</span><br><span
style="color:#339999;">34835</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">3319</span><br><span
style="color:#339999;">3319</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">38154</span><br><span
style="color:#339999;">38154</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=136.699 · df=1 · φ=0.060 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-english.learner" class="section level4">
<h4>english.learner</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
english.learner
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
0
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4387</span><br><span
style="color:#339999;">4464</span><br><span
style="color:#339933;">12.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">333</span><br><span
style="color:#339999;">256</span><br><span
style="color:#339933;">16.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">4720</span><br><span
style="color:#339999;">4720</span><br><span
style="color:#339933;">12.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">31700</span><br><span
style="color:#339999;">31623</span><br><span
style="color:#339933;">87.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1734</span><br><span
style="color:#339999;">1811</span><br><span
style="color:#339933;">83.9 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">33434</span><br><span
style="color:#339999;">33434</span><br><span
style="color:#339933;">87.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">36087</span><br><span
style="color:#339999;">36087</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">2067</span><br><span
style="color:#339999;">2067</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">38154</span><br><span
style="color:#339999;">38154</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=27.826 · df=1 · φ=0.027 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
</div>
<div id="section-high-school-accomplishments-variables"
class="section level3 tabset">
<h3 class="tabset">High school accomplishments variables</h3>
<p><strong>took.ACT:</strong> The p-value indicates that we can reject
the NULL hypothesis and acknowledge there may be a relationship between
whether an individual has meaningful employment in the same county as
their high school the year of graduation and whether the individual took
the ACT. However, the Cramer’s V^2 value is only .107 indicating a weak
relationship. Highlights from the table include;</p>
<ul>
<li>a significantly larger proportion of individuals that did NOT take
the ACT had meaningful employment in the same county as their high
school - 17.3% vs 9.9% of individuals that did take the ACT.</li>
<li>a significantly larger number of individuals that did NOT take the
ACT had meaningful employment in the same county as their high school -
2,197 observed vs. 1,567 expected.</li>
</ul>
<p><br></p>
<p><strong>ap.exam:</strong> The p-value indicates that we can reject
the NULL hypothesis and acknowledge there may be a relationship between
whether an individual has meaningful employment in the same county as
their high school the year of graduation and whether the individual took
the ACT. However, the Cramer’s V^2 value is only .064 indicating a weak
relationship. Highlights from the table include;</p>
<ul>
<li>a significantly larger proportion of individuals that did NOT take
the ap exam had meaningful employment in the same county as their high
school - 13.3% vs 7.5% of individuals that did take the AP exam.</li>
<li>a significantly larger number of individuals that did NOT take the
AP exam had meaningful employment in the same county as their high
school - 4,271 observed vs. 3,976 expected.</li>
</ul>
<p><br></p>
<p><strong>total.cte.coureses.taken:</strong> The p-value indicates we
can reject the null hypothesis and accept that there’s a relationship
between whether an individual works in the same county as their high
school and the number of CTE courses an individual has taken. ???</p>
<p><br></p>
<p><strong>cte.achievement:</strong> The p-value indicates that we can
reject the NULL hypothesis and acknowledge there may be a relationship
between whether an individual has meaningful employment in the same
county as their high school the year of graduation and the level of CTE
achievement. However, the Cramer’s V^2 value is only .074 indicating a
weak relationship. Highlights from the table include;</p>
<ul>
<li>A significantly larger proportion of individuals that was either a
CTE concentrator, or completor had meaningful employment in the same
county as their high school - 14.7% vs. 11.6% for CTE participant and
8.7% for individuals with no CTE.</li>
<li>This same group had a high number of individuals with meaningful
employment in the same county as their high school than what was
expected - 2,630 observed vs. 2,211 expected.</li>
</ul>
<p><br></p>
<p><strong>MCA.M:</strong> The p-value indicates we can reject the null
hypothesis and accept that there’s a relationship between whether an
individual works in the same county as their high school and their MCA
math score. ???</p>
<p><br></p>
<p><strong>MCA.R:</strong> The p-value indicates we can reject the null
hypothesis and accept that there’s a relationship between whether an
individual works in the same county as their high school and their MCA
reading score. ???</p>
<p><br></p>
<p><strong>MCA.S:</strong> The p-value indicates we can reject the null
hypothesis and accept that there’s a relationship between whether an
individual works in the same county as their high school and their MCA
science score. ???</p>
<p><br></p>
<div id="section-took.act" class="section level4">
<h4>took.ACT</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
took.ACT
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
No
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Yes
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2197</span><br><span
style="color:#339999;">1567</span><br><span
style="color:#339933;">17.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2523</span><br><span
style="color:#339999;">3153</span><br><span
style="color:#339933;">9.9 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">4720</span><br><span
style="color:#339999;">4720</span><br><span
style="color:#339933;">12.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">10469</span><br><span
style="color:#339999;">11099</span><br><span
style="color:#339933;">82.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">22965</span><br><span
style="color:#339999;">22335</span><br><span
style="color:#339933;">90.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">33434</span><br><span
style="color:#339999;">33434</span><br><span
style="color:#339933;">87.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">12666</span><br><span
style="color:#339999;">12666</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">25488</span><br><span
style="color:#339999;">25488</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">38154</span><br><span
style="color:#339999;">38154</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=432.159 · df=1 · φ=0.107 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-ap.exam" class="section level4">
<h4>ap.exam</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
ap.exam
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
0
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4271</span><br><span
style="color:#339999;">3976</span><br><span
style="color:#339933;">13.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">449</span><br><span
style="color:#339999;">744</span><br><span
style="color:#339933;">7.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">4720</span><br><span
style="color:#339999;">4720</span><br><span
style="color:#339933;">12.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">27872</span><br><span
style="color:#339999;">28167</span><br><span
style="color:#339933;">86.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">5562</span><br><span
style="color:#339999;">5267</span><br><span
style="color:#339933;">92.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">33434</span><br><span
style="color:#339999;">33434</span><br><span
style="color:#339933;">87.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">32143</span><br><span
style="color:#339999;">32143</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">6011</span><br><span
style="color:#339999;">6011</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">38154</span><br><span
style="color:#339999;">38154</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=157.577 · df=1 · φ=0.064 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-total.cte.courses.taken" class="section level4">
<h4>total.cte.courses.taken</h4>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)    
## dep.var         1   8066    8066   332.7 &lt;2e-16 ***
## Residuals   38152 924902      24                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = total.cte.courses.taken ~ dep.var, data = data)
## 
## $dep.var
##                     diff       lwr       upr p adj
## No match-Match -1.396456 -1.546508 -1.246404     0</code></pre>
<p><br></p>
</div>
<div id="section-cte.achievement" class="section level4">
<h4>cte.achievement</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="3">
cte.achievement
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
CTE Concentrator or<br>Completor
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
CTE Participant
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
No CTE
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2630</span><br><span
style="color:#339999;">2211</span><br><span
style="color:#339933;">14.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1304</span><br><span
style="color:#339999;">1389</span><br><span
style="color:#339933;">11.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">786</span><br><span
style="color:#339999;">1120</span><br><span
style="color:#339933;">8.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">4720</span><br><span
style="color:#339999;">4720</span><br><span
style="color:#339933;">12.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">15241</span><br><span
style="color:#339999;">15660</span><br><span
style="color:#339933;">85.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">9922</span><br><span
style="color:#339999;">9837</span><br><span
style="color:#339933;">88.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">8271</span><br><span
style="color:#339999;">7937</span><br><span
style="color:#339933;">91.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">33434</span><br><span
style="color:#339999;">33434</span><br><span
style="color:#339933;">87.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">17871</span><br><span
style="color:#339999;">17871</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">11226</span><br><span
style="color:#339999;">11226</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">9057</span><br><span
style="color:#339999;">9057</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">38154</span><br><span
style="color:#339999;">38154</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="5">
χ<sup>2</sup>=210.524 · df=2 · Cramer’s V=0.074 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-mca.m" class="section level4">
<h4>MCA.M</h4>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)    
## dep.var         1    520   519.8   472.5 &lt;2e-16 ***
## Residuals   35288  38819     1.1                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 2864 observations deleted due to missingness</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = MCA.M ~ dep.var, data = data)
## 
## $dep.var
##                     diff       lwr       upr p adj
## No match-Match 0.3647163 0.3318307 0.3976019     0</code></pre>
<p><br></p>
</div>
<div id="section-mca.r" class="section level4">
<h4>MCA.R</h4>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)    
## dep.var         1    383   382.6   410.9 &lt;2e-16 ***
## Residuals   35271  32840     0.9                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 2881 observations deleted due to missingness</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = MCA.R ~ dep.var, data = data)
## 
## $dep.var
##                     diff       lwr       upr p adj
## No match-Match 0.3137589 0.2834219 0.3440959     0</code></pre>
<p><br></p>
</div>
<div id="section-mca.s" class="section level4">
<h4>MCA.S</h4>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)    
## dep.var         1    264  263.68   333.7 &lt;2e-16 ***
## Residuals   28745  22714    0.79                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 9407 observations deleted due to missingness</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = MCA.S ~ dep.var, data = data)
## 
## $dep.var
##                     diff       lwr       upr p adj
## No match-Match 0.2918103 0.2605011 0.3231195     0</code></pre>
<p><br></p>
</div>
</div>
</div>
<div id="section-cross-tabs---time-x-grad-year-2"
class="section level2">
<h2>Cross tabs - Time X = grad year +2</h2>
<p><br></p>
<div id="section-demographic-variablestabset" class="section level3">
<h3>Demographic variables{tabset}</h3>
<p><strong>Race/Ethnicity:</strong> The crosstabs indicate a
relationship between whether an individual has meaningful employment in
the same county as their high school two years after graduation and the
individual’s race/ethnicity. The p-value was 0, however the Cramer’s V^2
value was 0.076, indicating a weak association. Highlights in the table
include;</p>
<ul>
<li>A larger proportion of black individuals (23.0%) had meaningful
employment in their high school county compared to AI, Asian/PI and
White individuals.</li>
<li>A larger observed number of Black individuals had meaningful
employment in the same county as their high school than what was
expected - 124 individuals vs. 94 expected.</li>
<li>A larger proportion of hispanic individuals (27.6%) had meaningful
employment in their high school county compared to all other
races/ethnicities.</li>
<li>A larger observed number of hispanic individuals had meaningful
employment in the same county as their high school than what was
expected - 569 observed vs. 359 expected.</li>
</ul>
<div id="section-raceethnicity-1" class="section level4">
<h4>Race/Ethnicity</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="5">
RaceEthnicity
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
AI
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Asian/PI
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Black
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Hispanic
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
White
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">43</span><br><span
style="color:#339999;">54</span><br><span
style="color:#339933;">13.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">117</span><br><span
style="color:#339999;">153</span><br><span
style="color:#339933;">13.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">124</span><br><span
style="color:#339999;">94</span><br><span
style="color:#339933;">23 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">569</span><br><span
style="color:#339999;">359</span><br><span
style="color:#339933;">27.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4684</span><br><span
style="color:#339999;">4877</span><br><span
style="color:#339933;">16.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">5537</span><br><span
style="color:#339999;">5537</span><br><span
style="color:#339933;">17.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">268</span><br><span
style="color:#339999;">257</span><br><span
style="color:#339933;">86.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">759</span><br><span
style="color:#339999;">723</span><br><span
style="color:#339933;">86.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">414</span><br><span
style="color:#339999;">444</span><br><span
style="color:#339933;">77 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1494</span><br><span
style="color:#339999;">1704</span><br><span
style="color:#339933;">72.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">23313</span><br><span
style="color:#339999;">23120</span><br><span
style="color:#339933;">83.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">26248</span><br><span
style="color:#339999;">26248</span><br><span
style="color:#339933;">82.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">311</span><br><span
style="color:#339999;">311</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">876</span><br><span
style="color:#339999;">876</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">538</span><br><span
style="color:#339999;">538</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">2063</span><br><span
style="color:#339999;">2063</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">27997</span><br><span
style="color:#339999;">27997</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">31785</span><br><span
style="color:#339999;">31785</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="7">
χ<sup>2</sup>=182.020 · df=4 · Cramer’s V=0.076 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
</div>
<div id="section-high-school-characteristic-variables-1"
class="section level3 tabset">
<h3 class="tabset">High school characteristic variables</h3>
<p><strong>Dem_Desc:</strong> The p-value indicates that we can reject
the null hypothesis and acknowledge that the variables may have a
relationship. The Cramer’s V^2 value is only 0.065, indicating that the
relationships are weak. Highlights from the table include;</p>
<ul>
<li>Individuals from entirely rural high schools had a significantly
lower proportion of individuals that had meaningful employment in the
same county as their high school two years after graduation - 11.6%
compared to 18.7% in town/rural mix and 17.4% in urban/town/rural
mix.</li>
<li>Individuals from entirely rural high schools had a significantly
lower observed number of individuals that had meaningful employment in
the same county as their high school two years after graduation - 550
observed vs. 824 expected.</li>
<li>Town/rural mix high schools had a significantly higher number of
individuals that had meaningful employment in the same county two years
after graduation than expected - 4,114 vs. 3,839 expected.</li>
</ul>
<p><br></p>
<p><strong>EDR:</strong> The p-value indicates that we can reject the
null hypothesis and acknowledge that the variables may have a
relationship. The Cramer’s V^2 value however is only 0.069, indicating
the associations are weak. Highlights in the table include;</p>
<ul>
<li>EDR 6W had the lowest proportion of individuals that had meaningful
employment in the same county as their high school two years after
graduation - 13% compared to 16.9% in EDR 8 and 20.3% in EDR 6E.</li>
<li>EDR 6W had a significantly lower number of individuals that had
meaningful employment in the same county as their high school the year
of graduation - 802 observed vs. 1,073 expected.</li>
</ul>
<p><br></p>
<p><strong>avg.unemployment.rate:</strong> The ANOVA table does indicate
a relationship between whether an individual has meaningful employment
in the same county as their high school two years after graduation and
the average unemployment rate in that county. ???</p>
<p><br></p>
<p><strong>wages.3year.avg:</strong> The ANOVA table does indicate a
relationship between whether an individual has meaningful employment in
the same county as their high school two years after graduation and the
average household income in that county. ???</p>
<div id="section-dem_desc-1" class="section level4">
<h4>Dem_Desc</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="3">
Dem_Desc
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Entirely rural
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Town/rural mix
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Urban/town/rural mix
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">550</span><br><span
style="color:#339999;">824</span><br><span
style="color:#339933;">11.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4114</span><br><span
style="color:#339999;">3839</span><br><span
style="color:#339933;">18.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">873</span><br><span
style="color:#339999;">874</span><br><span
style="color:#339933;">17.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">5537</span><br><span
style="color:#339999;">5537</span><br><span
style="color:#339933;">17.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4181</span><br><span
style="color:#339999;">3907</span><br><span
style="color:#339933;">88.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">17923</span><br><span
style="color:#339999;">18198</span><br><span
style="color:#339933;">81.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4144</span><br><span
style="color:#339999;">4143</span><br><span
style="color:#339933;">82.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">26248</span><br><span
style="color:#339999;">26248</span><br><span
style="color:#339933;">82.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">4731</span><br><span
style="color:#339999;">4731</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">22037</span><br><span
style="color:#339999;">22037</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">5017</span><br><span
style="color:#339999;">5017</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">31785</span><br><span
style="color:#339999;">31785</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="5">
χ<sup>2</sup>=134.308 · df=2 · Cramer’s V=0.065 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-edr-1" class="section level4">
<h4>EDR</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="3">
edr
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
EDR 6E- Southwest<br>Central
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
EDR 6W- Upper<br>Minnesota Valley
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
EDR 8 - Southwest
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2368</span><br><span
style="color:#339999;">2031</span><br><span
style="color:#339933;">20.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">802</span><br><span
style="color:#339999;">1073</span><br><span
style="color:#339933;">13 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2367</span><br><span
style="color:#339999;">2433</span><br><span
style="color:#339933;">16.9 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">5537</span><br><span
style="color:#339999;">5537</span><br><span
style="color:#339933;">17.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">9289</span><br><span
style="color:#339999;">9626</span><br><span
style="color:#339933;">79.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">5357</span><br><span
style="color:#339999;">5086</span><br><span
style="color:#339933;">87 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">11602</span><br><span
style="color:#339999;">11536</span><br><span
style="color:#339933;">83.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">26248</span><br><span
style="color:#339999;">26248</span><br><span
style="color:#339933;">82.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">11657</span><br><span
style="color:#339999;">11657</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">6159</span><br><span
style="color:#339999;">6159</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">13969</span><br><span
style="color:#339999;">13969</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">31785</span><br><span
style="color:#339999;">31785</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="5">
χ<sup>2</sup>=152.887 · df=2 · Cramer’s V=0.069 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-avg.unemployment.rate-1" class="section level4">
<h4>avg.unemployment.rate</h4>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)  
## dep.var         1      5   5.269   3.244 0.0717 .
## Residuals   31783  51625   1.624                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = avg.unemp.rate ~ dep.var, data = data)
## 
## $dep.var
##                      diff         lwr        upr     p adj
## No match-Match 0.03394622 -0.00299442 0.07088686 0.0716889</code></pre>
<p><br></p>
</div>
<div id="section-wages.3yr.avg-1" class="section level4">
<h4>wages.3yr.avg</h4>
<pre><code>##                Df    Sum Sq   Mean Sq F value   Pr(&gt;F)    
## dep.var         1 2.678e+08 267821611   19.71 9.05e-06 ***
## Residuals   31783 4.319e+11  13588715                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = wages.3year.avg ~ dep.var, data = data)
## 
## $dep.var
##                     diff       lwr       upr p adj
## No match-Match -242.0185 -348.8657 -135.1713 9e-06</code></pre>
<p><br></p>
</div>
</div>
<div id="section-high-school-enrollment-variables-1"
class="section level3 tabset">
<h3 class="tabset">High school enrollment variables</h3>
<p><strong>LimitedEnglishProficiencyIndicator:</strong> The p-value
indicates that we can not reject the NULL hypothesis.</p>
<p><br></p>
<p><strong>pseo.participant:</strong> The p-value indicates that we can
reject the NULL hypothesis and acknowledge there may be a relationship
between whether an individual has meaningful employment in the same
county as their high school two years after graduation and whether they
participated in PSEO classes. However, the Cramer’s V^2 value is only
.110 indicating a weak relationship. Highlights from the table
include;</p>
<ul>
<li>A significantly larger proportion of individuals that did NOT
participate in PSEO classes had meaningful employment in the same county
as their high school the year of graduation - 20.3% vs. 11.5% for
individuals that did participate in PSEO.</li>
<li>A significantly larger number of individuals that did NOT
participate in PSEO had meaningful employment in the same county as
their high school the year of graduation - 4,348 observed vs. 3,729
expected.</li>
</ul>
<p><br></p>
<p><strong>non.english.home:</strong> The p-value indicates that we can
reject the NULL hypothesis and acknowledge there may be a relationship
between whether an individual has meaningful employment in the same
county as their high school two years after graduation and whether the
individual had someone in their home where english wasn’t the primary
language. However, the Cramer’s V^2 value is only .050 indicating a weak
relationship. Highlights from the table include;</p>
<ul>
<li>A significantly larger proportion of individuals where english
wasn’t the primary language at home had meaningful employment in the
same county as their high school the year of graduation - 23.7%
vs. 16.9% for individuals where English was the primary language at
home.</li>
<li>The observed vs expected was also significantly different for this
group - 616 observed vs. 452 expected.</li>
</ul>
<p><br></p>
<p><strong>english.learner</strong>: The p-value indicates that we can
reject the NULL hypothesis and acknowledge there may be a relationship
between whether an individual has meaningful employment in the same
county as their high school two years after graduation and whether the
individual had someone in their home where english wasn’t the primary
language. However, the Cramer’s V^2 value is only .031 indicating a weak
relationship. Highlights from the table include;</p>
<ul>
<li>A larger proportion of individuals categorized as english learners
had meaningful employment in the same county as their high school -
22.5% vs. 17.2% of individuals not designated as english learners.</li>
<li>This same group had a larger number of individuals that expected -
355 observed vs. 275 expected.</li>
</ul>
<div id="section-limitedenglishproficiencyindicator-1"
class="section level4">
<h4>LimitedEnglishProficiencyIndicator</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
LimitedEnglishProficiencyIndicator
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
N
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Y
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">5417</span><br><span
style="color:#339999;">5437</span><br><span
style="color:#339933;">17.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">120</span><br><span
style="color:#339999;">100</span><br><span
style="color:#339933;">20.9 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">5537</span><br><span
style="color:#339999;">5537</span><br><span
style="color:#339933;">17.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">25793</span><br><span
style="color:#339999;">25773</span><br><span
style="color:#339933;">82.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">455</span><br><span
style="color:#339999;">475</span><br><span
style="color:#339933;">79.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">26248</span><br><span
style="color:#339999;">26248</span><br><span
style="color:#339933;">82.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">31210</span><br><span
style="color:#339999;">31210</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">575</span><br><span
style="color:#339999;">575</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">31785</span><br><span
style="color:#339999;">31785</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=4.602 · df=1 · Cramer’s V=0.012 · p=0.032
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-pseo.participant-1" class="section level4">
<h4>pseo.participant</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
pseo.participant
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
0
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4348</span><br><span
style="color:#339999;">3729</span><br><span
style="color:#339933;">20.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1189</span><br><span
style="color:#339999;">1808</span><br><span
style="color:#339933;">11.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">5537</span><br><span
style="color:#339999;">5537</span><br><span
style="color:#339933;">17.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">17056</span><br><span
style="color:#339999;">17675</span><br><span
style="color:#339933;">79.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">9192</span><br><span
style="color:#339999;">8573</span><br><span
style="color:#339933;">88.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">26248</span><br><span
style="color:#339999;">26248</span><br><span
style="color:#339933;">82.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">21404</span><br><span
style="color:#339999;">21404</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">10381</span><br><span
style="color:#339999;">10381</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">31785</span><br><span
style="color:#339999;">31785</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=380.877 · df=1 · Cramer’s V=0.110 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-non.english.home-1" class="section level4">
<h4>non.english.home</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
non.english.home
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
0
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4921</span><br><span
style="color:#339999;">5085</span><br><span
style="color:#339933;">16.9 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">616</span><br><span
style="color:#339999;">452</span><br><span
style="color:#339933;">23.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">5537</span><br><span
style="color:#339999;">5537</span><br><span
style="color:#339933;">17.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">24270</span><br><span
style="color:#339999;">24106</span><br><span
style="color:#339933;">83.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1978</span><br><span
style="color:#339999;">2142</span><br><span
style="color:#339933;">76.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">26248</span><br><span
style="color:#339999;">26248</span><br><span
style="color:#339933;">82.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">29191</span><br><span
style="color:#339999;">29191</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">2594</span><br><span
style="color:#339999;">2594</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">31785</span><br><span
style="color:#339999;">31785</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=78.119 · df=1 · φ=0.050 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-english.learner-1" class="section level4">
<h4>english.learner</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
english.learner
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
0
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">5182</span><br><span
style="color:#339999;">5262</span><br><span
style="color:#339933;">17.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">355</span><br><span
style="color:#339999;">275</span><br><span
style="color:#339933;">22.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">5537</span><br><span
style="color:#339999;">5537</span><br><span
style="color:#339933;">17.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">25024</span><br><span
style="color:#339999;">24944</span><br><span
style="color:#339933;">82.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1224</span><br><span
style="color:#339999;">1304</span><br><span
style="color:#339933;">77.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">26248</span><br><span
style="color:#339999;">26248</span><br><span
style="color:#339933;">82.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">30206</span><br><span
style="color:#339999;">30206</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1579</span><br><span
style="color:#339999;">1579</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">31785</span><br><span
style="color:#339999;">31785</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=29.231 · df=1 · φ=0.031 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
</div>
<div id="section-high-school-accomplishments-variables-1"
class="section level3 tabset">
<h3 class="tabset">High school accomplishments variables</h3>
<p><strong>took.ACT:</strong> The p-value indicates that we can reject
the NULL hypothesis and acknowledge there may be a relationship between
whether an individual has meaningful employment in the same county as
their high school two years after graduation and whether the individual
took the ACT. However, the Cramer’s V^2 value is only .139 indicating a
weak relationship. Highlights from the table include;</p>
<ul>
<li>a significantly larger proportion of individuals that did NOT take
the ACT had meaningful employment in the same county as their high
school - 24.5% vs 13.5% of individuals that did take the ACT.</li>
<li>a significantly larger number of individuals that did NOT take the
ACT had meaningful employment in the same county as their high school -
2,763 observed vs. 1,962 expected.</li>
</ul>
<p><br></p>
<p><strong>ap.exam:</strong> The p-value indicates that we can reject
the NULL hypothesis and acknowledge there may be a relationship between
whether an individual has meaningful employment in the same county as
their high school the year of graduation and whether the individual took
the ACT. However, the Cramer’s V^2 value is only .083 indicating a weak
relationship. Highlights from the table include;</p>
<ul>
<li>a significantly larger proportion of individuals that did NOT take
the ap exam had meaningful employment in the same county as their high
school - 18.8% vs 10.2% of individuals that did take the AP exam.</li>
<li>a significantly larger number of individuals that did NOT take the
AP exam had meaningful employment in the same county as their high
school - 5,027 observed vs. 4,664 expected.</li>
</ul>
<p><br></p>
<p><strong>total.cte.coureses.taken:</strong> The p-value indicates we
can reject the null hypothesis and accept that there’s a relationship
between whether an individual works in the same county as their high
school two years after graduation and the number of CTE courses an
individual has taken. ???</p>
<p><br></p>
<p><strong>cte.achievement:</strong> The p-value indicates that we can
reject the NULL hypothesis and acknowledge there may be a relationship
between whether an individual has meaningful employment in the same
county as their high school two years after graduation and the level of
CTE achievement. However, the Cramer’s V^2 value is only .094 indicating
a weak relationship. Highlights from the table include;</p>
<ul>
<li>A significantly larger proportion of individuals that was either a
CTE concentrator, or completor had meaningful employment in the same
county as their high school - 20.7% vs. 16.8% for CTE participant and
11.7% for individuals with no CTE.</li>
<li>This same group had a high number of individuals with meaningful
employment in the same county as their high school than what was
expected - 3,038 observed vs. 2,555 expected.</li>
</ul>
<p><br></p>
<p><strong>MCA.M:</strong> The p-value indicates we can reject the null
hypothesis and accept that there’s a relationship between whether an
individual works in the same county as their high school two years after
graduation and their MCA math score. ???</p>
<p><br></p>
<p><strong>MCA.R:</strong> The p-value indicates we can reject the null
hypothesis and accept that there’s a relationship between whether an
individual works in the same county as their high school two years after
graduation and their MCA reading score. ???</p>
<p><br></p>
<p><strong>MCA.S:</strong> The p-value indicates we can reject the null
hypothesis and accept that there’s a relationship between whether an
individual works in the same county as their high school two years after
graduation and their MCA science score. ???</p>
<p><br></p>
<div id="section-took.act-1" class="section level4">
<h4>took.ACT</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
took.ACT
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
No
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Yes
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2763</span><br><span
style="color:#339999;">1962</span><br><span
style="color:#339933;">24.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2774</span><br><span
style="color:#339999;">3575</span><br><span
style="color:#339933;">13.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">5537</span><br><span
style="color:#339999;">5537</span><br><span
style="color:#339933;">17.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">8499</span><br><span
style="color:#339999;">9300</span><br><span
style="color:#339933;">75.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">17749</span><br><span
style="color:#339999;">16948</span><br><span
style="color:#339933;">86.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">26248</span><br><span
style="color:#339999;">26248</span><br><span
style="color:#339933;">82.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">11262</span><br><span
style="color:#339999;">11262</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">20523</span><br><span
style="color:#339999;">20523</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">31785</span><br><span
style="color:#339999;">31785</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=612.795 · df=1 · φ=0.139 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-ap.exam-1" class="section level4">
<h4>ap.exam</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
ap.exam
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
0
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">5027</span><br><span
style="color:#339999;">4664</span><br><span
style="color:#339933;">18.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">510</span><br><span
style="color:#339999;">873</span><br><span
style="color:#339933;">10.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">5537</span><br><span
style="color:#339999;">5537</span><br><span
style="color:#339933;">17.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">21749</span><br><span
style="color:#339999;">22112</span><br><span
style="color:#339933;">81.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4499</span><br><span
style="color:#339999;">4136</span><br><span
style="color:#339933;">89.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">26248</span><br><span
style="color:#339999;">26248</span><br><span
style="color:#339933;">82.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">26776</span><br><span
style="color:#339999;">26776</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">5009</span><br><span
style="color:#339999;">5009</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">31785</span><br><span
style="color:#339999;">31785</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=215.973 · df=1 · φ=0.083 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-total.cte.courses.taken-1" class="section level4">
<h4>total.cte.courses.taken</h4>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)    
## dep.var         1  10603   10603   455.6 &lt;2e-16 ***
## Residuals   31783 739733      23                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = total.cte.courses.taken ~ dep.var, data = data)
## 
## $dep.var
##                     diff       lwr       upr p adj
## No match-Match -1.522777 -1.662611 -1.382943     0</code></pre>
<p><br></p>
</div>
<div id="section-cte.achievement-1" class="section level4">
<h4>cte.achievement</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="3">
cte.achievement
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
CTE Concentrator or<br>Completor
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
CTE Participant
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
No CTE
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3038</span><br><span
style="color:#339999;">2555</span><br><span
style="color:#339933;">20.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1623</span><br><span
style="color:#339999;">1678</span><br><span
style="color:#339933;">16.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">876</span><br><span
style="color:#339999;">1304</span><br><span
style="color:#339933;">11.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">5537</span><br><span
style="color:#339999;">5537</span><br><span
style="color:#339933;">17.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">11630</span><br><span
style="color:#339999;">12113</span><br><span
style="color:#339933;">79.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">8011</span><br><span
style="color:#339999;">7956</span><br><span
style="color:#339933;">83.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">6607</span><br><span
style="color:#339999;">6179</span><br><span
style="color:#339933;">88.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">26248</span><br><span
style="color:#339999;">26248</span><br><span
style="color:#339933;">82.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">14668</span><br><span
style="color:#339999;">14668</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">9634</span><br><span
style="color:#339999;">9634</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">7483</span><br><span
style="color:#339999;">7483</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">31785</span><br><span
style="color:#339999;">31785</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="5">
χ<sup>2</sup>=282.490 · df=2 · Cramer’s V=0.094 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-mca.m-1" class="section level4">
<h4>MCA.M</h4>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)    
## dep.var         1    719   718.8   658.2 &lt;2e-16 ***
## Residuals   29530  32252     1.1                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 2253 observations deleted due to missingness</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = MCA.M ~ dep.var, data = data)
## 
## $dep.var
##                     diff       lwr       upr p adj
## No match-Match 0.4067462 0.3756718 0.4378206     0</code></pre>
<p><br></p>
</div>
<div id="section-mca.r-1" class="section level4">
<h4>MCA.R</h4>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)    
## dep.var         1    494   494.0     549 &lt;2e-16 ***
## Residuals   29384  26438     0.9                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 2399 observations deleted due to missingness</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = MCA.R ~ dep.var, data = data)
## 
## $dep.var
##                     diff       lwr       upr p adj
## No match-Match 0.3383069 0.3100081 0.3666057     0</code></pre>
<p><br></p>
</div>
<div id="section-mca.s-1" class="section level4">
<h4>MCA.S</h4>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)    
## dep.var         1    344   344.1   459.6 &lt;2e-16 ***
## Residuals   22999  17215     0.7                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 8784 observations deleted due to missingness</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = MCA.S ~ dep.var, data = data)
## 
## $dep.var
##                     diff       lwr      upr p adj
## No match-Match 0.3203567 0.2910685 0.349645     0</code></pre>
<p><br></p>
</div>
</div>
<div id="section-post-secondary" class="section level3 tabset">
<h3 class="tabset">Post-secondary</h3>
<p><strong>ps.grad:</strong> The p-value indicates that we can reject
the NULL hypothesis and acknowledge there may be a relationship between
whether an individual has meaningful employment in the same county as
their high school two years after graduation and whether the individual
graduated from a post-secondary institution.However, the Cramer’s V^2
value is only .115 indicating a weak relationship. Highlights from the
table include;</p>
<ul>
<li>a significantly larger proportion of individuals that did NOT
graduate from a post-secondary institution had meaningful employment in
the same county as their high school - 22.2% vs 13.4% of individuals
that graduated from a post-seconary institution.</li>
<li>a significantly larger number of individuals that did NOT graduate
from a post-secondary institution had meaningful employment in the same
county as their high school - 3,231 observed vs. 2,539 expected.</li>
</ul>
<p><br></p>
<p><strong>attended.ps:</strong> The p-value indicates that we can
reject the NULL hypothesis and acknowledge there may be a relationship
between whether an individual has meaningful employment in the same
county as their high school two years after graduation and whether the
individual attended a post-secondary institution. However, the Cramer’s
V^2 value is only .071 indicating a weak relationship. Highlights from
the table include;</p>
<ul>
<li>a significantly larger proportion of individuals that did NOT attend
post-secondary had meaningful employment in the same county as their
high school - 22.5% vs 16% of individuals that attended a post-secondary
institution.</li>
<li>a significantly larger number of individuals that did NOT attend a
post-secondary institution had meaningful employment in the same county
as their high school - 1,580 observed vs. 1,223 expected.</li>
</ul>
<p><br></p>
<p><strong>ps.grad.InstitutionSector:</strong> The p-value indicates
that we can reject the NULL hypothesis and acknowledge there may be a
relationship between whether an individual has meaningful employment in
the same county as their high school two years after graduation and
whether the individual attended a post-secondary institution. However,
the Cramer’s V^2 value is only .209 indicating a weak relationship.
Highlights from the table include;</p>
<ul>
<li>A significantly larger proportion of individuals that graduated from
a public, 2-year institutions (code 4) had meaningful employment in the
same county as their high school two years after graduation - 25.5%
compared to less than 20% for all other institutions.</li>
<li>This same group of individuals had more people with meaningful
employment in the same county as their high school than expected - 1,439
vs. 984 expected.</li>
<li>A significantly larger proportion of individuals that never attended
post secondary had meaningful employment in the same county as their
high school two years after graduating - 22.5%.</li>
<li>These same individuals a significantly higher number have meaningful
employment in the same county as their high school than expected - 1,580
observed vs. 1,223 expected.</li>
<li>A significantly larger proportion of individuals that attend post
secondary but never graduated had meaningful employment in the same
county as their high school two years after graduating - 21.8%.</li>
<li>These same individuals had a significantly higher number of people
have meaningful employment in the same county as their high school two
years after graduating - 1,659 observed vs. 1,328 expected.</li>
<li>A significantly lower proportion of individuals that graduated from
a public, 4 year college had meaningful employment in the same county as
their high school two years after graduation - 6.8%.</li>
<li>These same individuals had a significantly lower number of people
that had meaningful employment in the same county as their high school -
482 observed vs. 1,243 expected.</li>
</ul>
<p><br></p>
<p><strong>highest.cred.level:</strong> The p-value indicates that we
can reject the NULL hypothesis and acknowledge there may be a
relationship between whether an individual has meaningful employment in
the same county as their high school two years after graduation and
whether the highest credential an individual received. However, the
Cramer’s V^2 value is only .201 indicating a weak relationship.
Highlights from the table include;</p>
<ul>
<li>a significantly larger proportion of individuals that received an
Associate degree or Less than Associate degree had meaningful employment
in the same county as their high school - 21.7% of individuals with
Associate degree and 22.5% for individuals with less than associate
degree.</li>
<li>a significantly larger number of individuals that received an
Associate degree had meaningful employment in the same county as their
high school than expected - 849 observed vs. 682 expected.</li>
<li>a significantly larger number of individuals that received less than
an Associate degree had meaningful employment in the same county as
their high school than expected - 4,154 observed vs. 3,215
expected.</li>
</ul>
<p><br></p>
<div id="section-ps.grad" class="section level4">
<h4>ps.grad</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
ps.grad
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
0
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3231</span><br><span
style="color:#339999;">2539</span><br><span
style="color:#339933;">22.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2306</span><br><span
style="color:#339999;">2998</span><br><span
style="color:#339933;">13.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">5537</span><br><span
style="color:#339999;">5537</span><br><span
style="color:#339933;">17.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">11342</span><br><span
style="color:#339999;">12034</span><br><span
style="color:#339933;">77.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">14906</span><br><span
style="color:#339999;">14214</span><br><span
style="color:#339933;">86.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">26248</span><br><span
style="color:#339999;">26248</span><br><span
style="color:#339933;">82.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">14573</span><br><span
style="color:#339999;">14573</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">17212</span><br><span
style="color:#339999;">17212</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">31785</span><br><span
style="color:#339999;">31785</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=421.649 · df=1 · φ=0.115 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-attended.ps" class="section level4">
<h4>attended.ps</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
attended.ps
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
No
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Yes
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1580</span><br><span
style="color:#339999;">1223</span><br><span
style="color:#339933;">22.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3957</span><br><span
style="color:#339999;">4314</span><br><span
style="color:#339933;">16 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">5537</span><br><span
style="color:#339999;">5537</span><br><span
style="color:#339933;">17.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">5439</span><br><span
style="color:#339999;">5796</span><br><span
style="color:#339933;">77.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">20809</span><br><span
style="color:#339999;">20452</span><br><span
style="color:#339933;">84 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">26248</span><br><span
style="color:#339999;">26248</span><br><span
style="color:#339933;">82.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">7019</span><br><span
style="color:#339999;">7019</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">24766</span><br><span
style="color:#339999;">24766</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">31785</span><br><span
style="color:#339999;">31785</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=161.794 · df=1 · φ=0.071 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-ps.grad.institutionsector" class="section level4">
<h4>ps.grad.InstitutionSector</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="8">
ps.grad.InstitutionSector
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
10
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
11
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
2
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
3
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
4
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Did not grad
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Never attended ps
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">482</span><br><span
style="color:#339999;">1243</span><br><span
style="color:#339933;">6.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">238</span><br><span
style="color:#339999;">286</span><br><span
style="color:#339933;">14.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">11</span><br><span
style="color:#339999;">11</span><br><span
style="color:#339933;">16.9 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">82</span><br><span
style="color:#339999;">423</span><br><span
style="color:#339933;">3.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">46</span><br><span
style="color:#339999;">39</span><br><span
style="color:#339933;">20.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1439</span><br><span
style="color:#339999;">984</span><br><span
style="color:#339933;">25.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1659</span><br><span
style="color:#339999;">1328</span><br><span
style="color:#339933;">21.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1580</span><br><span
style="color:#339999;">1223</span><br><span
style="color:#339933;">22.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">5537</span><br><span
style="color:#339999;">5537</span><br><span
style="color:#339933;">17.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">6651</span><br><span
style="color:#339999;">5890</span><br><span
style="color:#339933;">93.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1402</span><br><span
style="color:#339999;">1354</span><br><span
style="color:#339933;">85.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">54</span><br><span
style="color:#339999;">54</span><br><span
style="color:#339933;">83.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2349</span><br><span
style="color:#339999;">2008</span><br><span
style="color:#339933;">96.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">179</span><br><span
style="color:#339999;">186</span><br><span
style="color:#339933;">79.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4212</span><br><span
style="color:#339999;">4667</span><br><span
style="color:#339933;">74.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">5962</span><br><span
style="color:#339999;">6293</span><br><span
style="color:#339933;">78.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">5439</span><br><span
style="color:#339999;">5796</span><br><span
style="color:#339933;">77.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">26248</span><br><span
style="color:#339999;">26248</span><br><span
style="color:#339933;">82.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">7133</span><br><span
style="color:#339999;">7133</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1640</span><br><span
style="color:#339999;">1640</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">65</span><br><span
style="color:#339999;">65</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">2431</span><br><span
style="color:#339999;">2431</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">225</span><br><span
style="color:#339999;">225</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">5651</span><br><span
style="color:#339999;">5651</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">7621</span><br><span
style="color:#339999;">7621</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">7019</span><br><span
style="color:#339999;">7019</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">31785</span><br><span
style="color:#339999;">31785</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="10">
χ<sup>2</sup>=1389.093 · df=7 · Cramer’s V=0.209 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
<div id="section-highest.cred.level" class="section level4">
<h4>highest.cred.level</h4>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Test
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
<code>County match</code>
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="4">
highest.cred.level
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Associate degree
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Bachelor degree
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Less than Associate<br>Degree
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Master degree or<br>higher
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">849</span><br><span
style="color:#339999;">682</span><br><span
style="color:#339933;">21.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">532</span><br><span
style="color:#339999;">1623</span><br><span
style="color:#339933;">5.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4154</span><br><span
style="color:#339999;">3215</span><br><span
style="color:#339933;">22.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2</span><br><span
style="color:#339999;">17</span><br><span
style="color:#339933;">2 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">5537</span><br><span
style="color:#339999;">5537</span><br><span
style="color:#339933;">17.4 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No match
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3065</span><br><span
style="color:#339999;">3232</span><br><span
style="color:#339933;">78.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">8785</span><br><span
style="color:#339999;">7694</span><br><span
style="color:#339933;">94.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">14300</span><br><span
style="color:#339999;">15239</span><br><span
style="color:#339933;">77.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">98</span><br><span
style="color:#339999;">83</span><br><span
style="color:#339933;">98 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">26248</span><br><span
style="color:#339999;">26248</span><br><span
style="color:#339933;">82.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">3914</span><br><span
style="color:#339999;">3914</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">9317</span><br><span
style="color:#339999;">9317</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">18454</span><br><span
style="color:#339999;">18454</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">100</span><br><span
style="color:#339999;">100</span><br><span
style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">31785</span><br><span
style="color:#339999;">31785</span><br><span
style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="6">
χ<sup>2</sup>=1286.629 · df=3 · Cramer’s V=0.201 · p=0.000
</td>
</tr>
</table>
<p><br></p>
</div>
</div>
</div>
<div id="section-cross-tabs---time-x-grad-year-7"
class="section level2">
<h2>Cross tabs - Time X = grad year +7</h2>
<p><br></p>
<div id="section-demographic-variables-1" class="section level3">
<h3>Demographic variables</h3>
<p><br></p>
</div>
<div id="section-high-school-characteristic-variables-2"
class="section level3">
<h3>High school characteristic variables</h3>
<p><br></p>
</div>
<div id="section-high-school-enrollment-variables-2"
class="section level3">
<h3>High school enrollment variables</h3>
<p><br></p>
</div>
<div id="section-high-school-accomplishments-variables-2"
class="section level3">
<h3>High school accomplishments variables</h3>
<p><br></p>
</div>
<div id="section-post-secondary-1" class="section level3">
<h3>Post-secondary</h3>
<p><br></p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#section-TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
